### PR TITLE
Improve Github templates + README for contributions and support

### LINKED ISSUE #1875: Improve contributing documentation
- [ ] Review and organize:
  - https://github.com/Kitware/vtk-js#reporting-bugs
  - https://github.com/Kitware/vtk-js#contributing
  - https://github.com/Kitware/vtk-js/blob/master/CONTRIBUTING.md
- [x] Document use of [issue labels](https://github.com/Kitware/vtk-js/labels) (readme + issue template)
- [x] Clarify when to use [discourse](https://discourse.vtk.org/c/web/9) vs issue tracker (readme + issue template)

### PR DESCRIPTION
**Pull request by agirault**
### Context

Fix #1875

### Changes

- Updated GitHub templates for issues and pull requests
- Reorganized a section of the `README.md`

### Results

- issue labels automatically assigned (test [here](https://github.com/agirault/vtk-js/issues/new/choose))
Screen Shot 2021-04-26 at 5 52 44 PM

- "Using vtk.js" section in `README.md` (visible [here](https://github.com/agirault/vtk-js/blob/new-issue-templates/README.md#using-vtkjs))

### Testing

N/A, doc/chore only

### CODE REVIEW

**Comment by agirault** [comment]
FYI @daker, thanks for the initial work on this!

**Review by jourdain — APPROVED** [review]
LGTM

**Comment by daker** [comment]
@agirault regarding the documentation, we did start a big chunk of work where we add typescript definitions which also includes the documentation, and remove api.md progressively.

.d.ts: https://github.com/Kitware/vtk-js/blob/master/Sources/Rendering/Core/Camera/index.d.ts
online: https://kitware.github.io/vtk-js/api/Rendering_Core_Camera.html

**Comment by agirault** [comment]
@daker: nice! Do you recommend we update the `CONTRIBUTING.md` doc to document that? Or were you thinking of something in those current changes?

**Comment by daker** [comment]
@agirault it would be good if it's added to the pull request template, so we can keep the JS & TS api in sync

[ ] Documentation and TS defs was updated to match those changes

**Comment by agirault** [comment]
@daker I'm looking back at this. I can't find any other mention of the TS doc apart from your comment above. Ideally, [we could address this](https://github.com/Kitware/vtk-js/pull/1893#issuecomment-832987688), then update the PR template to link to that as well. Thoughts?

**Pull request merged**
