### PR TITLE
fix(ProxyManager): Optionally set proxy to active, if possible

### PR DESCRIPTION
**Pull request by floryst**
setActive is default true, so code must explicitly disable this.

### CODE REVIEW

**Comment by floryst** [comment]
Do we want `setActive` default to true or false?

**Comment by jourdain** [comment]
I was thinking it could be nice to have a `activate()` method on any proxy.
Then in the config we could choose the behavior (auto activate or not). And by default they become active. 
That way the method call won't have the extra arg.
Basically only the source need to be 'patch' to become valid and maybe Representation but Views should be fine.

What do you think? Maybe the default should not be active...

**Comment by floryst** [comment]
I like the idea of having an `activate()` method. It also reduces code duplication with `setActive*` methods in ProxyManager/core.js. Would it make sense to have `activate` on all proxies, or just ones that make sense (e.g. Views and Sources, but not Representations)?

I think the default should be not active, so applications should clearly specify they are activating a proxy.

**Comment by jourdain** [comment]
I think all proxy should have a `activate()` (inside macro.proxy).

Then the default should be not to activate a new proxy.

**Comment by jourdain** [comment]
But it could be nice to also specify when a new should automatically activate the created proxy in the config. With the default being to not do it.

**Comment by floryst** [comment]
Ok, I'll add an activate. And agreed, having an `activateOnCreate` config option for a proxy is useful.

**Comment by floryst** [comment]
I've pushed a working implementation.

**Comment by jourdain** [comment]
LGTM

**Pull request merged**
