### PR TITLE
feat(ITKHelper): Add convertVtkToItkImage

### PR DESCRIPTION
**Pull request by boucaud**
Following up on https://github.com/InsightSoftwareConsortium/itk-js/issues/260

This merge request adds a convertVtkToItkImage function to ITKHelper. It also brings a minor change to convertItkToVtkImage to use the ITKPixelTypes enum instead of integers.

### CODE REVIEW

**Comment by boucaud** [comment]
@finetjul

**Comment by finetjul** [comment]
LGTM

**Comment by floryst** [comment]
Check errors look to be unrelated to the commit, so I'll merge this.

**Pull request merged**
