### PR TITLE
fix: Add ImageCropFilter and ImageCroppingWidget to exports

### LINKED ISSUE #1029: export vtkImageCropFilter and vtkImageCroppingWidget in default

### PR DESCRIPTION
**Pull request by floryst**
Fixes #1029

### CODE REVIEW

**Comment by agirault** [comment]
Thanks! Since you're adding more exports, could you maybe export the annotatedCubeActor [presets](https://github.com/Kitware/vtk-js/blob/9063bb4db9da420f5e127d72a9cba60802f6624b/Sources/Rendering/Core/AnnotatedCubeActor/Presets.js) in [here](https://github.com/Kitware/vtk-js/blob/9063bb4db9da420f5e127d72a9cba60802f6624b/Sources/Rendering/Core/AnnotatedCubeActor/index.js#L191)?

**Comment by agirault** [comment]
Also, the first commit message is wrong, you are exporting ImageCropFilter not PaintFilter

**Comment by floryst** [comment]
Oh thanks, good catch. Was working on the paint filter right before this...

**Pull request merged**
