### PR TITLE
fix(Rendering): make ImageMapper use the ImageSlice matrix

### PR DESCRIPTION
**Pull request by martinken**
The prior code was ignoring the ImageSlice pose (matrix)

### CODE REVIEW

**Comment by martinken** [comment]
@jourdain big changes to package*  hmmm

**Comment by jourdain** [comment]
yep... but your babel is up-to-date... As you told me it was important for you. ;-)

**Comment by jourdain** [comment]
I let you merge

**Comment by martinken** [comment]
OK Just wanted to make sure the package changes were normal.

**Pull request merged**
