### PR TITLE
fix(Sources/Interaction/Widgets/LabelRepresentation/index.js): Lines …

### PR DESCRIPTION
**Pull request by RemiCecchinato**
Lines are now properly splitted.

### CODE REVIEW

**Comment by finetjul** [comment]
fix(LabelWidget) should be enough.

**Comment by jourdain** [comment]
The commit message should be updated to follow what @finetjul suggest in order to get the proper changelog generation.

Thanks for your contribution.

**Comment by martinken** [comment]
@jourdain look good? If so merge?

**Pull request merged**
