### PR TITLE
fix(LineWidget): onModified memory leak

### PR DESCRIPTION
**Pull request by floryst**
### Context

#3062 reported a memory leak with vtkLineWidget. It remains to be seen if widgets generally leak memory.

### Results

- Line widget no longer leaks memory

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
N/A

### CODE REVIEW

**Review by finetjul — APPROVED** [review]
Could a unit test detect memory leaks on widgets automatically?

**Comment by floryst** [comment]
There's `performance.memory`, but it's deprecated, doesn't have firefox support, and is likely a granular measure to avoid fingerprinting. The other approach would be to use a WeakMap, but that would require being able to reliably trigger GC, which we can't.

**Comment by finetjul** [comment]
@floryst could we inject code in `macro.obj()` or `delete()` to keep track of created/deleted objects ?

**Comment by floryst** [comment]
Yes, that can help track leaked objects, but it would be noisy b/c there's a lot of vtk.js objects that stick around for the duration of a scene. However, I don't know if it'll help with objects we don't directly create (such as nested widget states), since we'd want to use WeakMap to avoid holding a strong reference to tracked objects. Did you have some specific mechanism in mind?

**Pull request merged**
