### PR TITLE
fix(wslinkclient): changed type for protocols to access protocol as…

### LINKED ISSUE #2569: Type error for getRemote function on vtkWSLClient
## Context

I am trying to connect to a paraview server using `RemoteView` (here is the [RemoteView example](https://kitware.github.io/vtk-js/examples/RemoteView.html)). I have added a few protocols (ProxyManager, ViewPort, etc.) and I am trying to access these once it gets connected to the paraview server.

```js
  const client = vtkWSLinkClient.newInstance({
    protocols: {
      proxyManager: ProxyManager,
      fileManager: FileListing,
      viewManager: ViewPort,
    },
  });
```

```js
  client
    .connect(serverConfig)
    .then((validClient) => {
      console.log('connected image stream');
      connectImageStream(validClient.getConnection().getSession());
      const s = validClient.getConnection().getSession();
      const pm = validClient.getRemote().proxyManager;
      const vm = validClient.getRemote().viewManager;
```

## Description

Now I am trying to add types in this file. Declaring types for the protocols would lead me to this error

image

Could we change the type for `getRemote` to fix this ?

https://github.com/Kitware/vtk-js/blob/0b1de784be7cad010a1ab17f840d78839a07f628/Sources/IO/Core/WSLinkClient/index.d.ts#L133

```ts
  getRemote: () => Record<string, any>
```

### PR DESCRIPTION
**Pull request by Nikhil216**
… property on remote

fix #2569

### CODE REVIEW

**Comment by jourdain** [comment]
Since wslink releases are not that common, you may want to trigger one so you can get your definition. Just replace `docs(...` by `fix(...`. 

Otherwise everything looks good. Thanks for contributing!

**Comment by jourdain** [comment]
You need to amend your commit and force push. If I merge your change right now, nothing will happen as semantic-release will only see a `docs(....`

**Comment by Nikhil216** [comment]
Thanks for all the help @jourdain. I guess this should do the job.

**Comment by jourdain** [comment]
Thanks! I'll merge it once the CI comes back.

**Pull request merged**
