### PR TITLE
fix(shapewidget): upgrade placePoint methods to not propagate Interac…

### PR DESCRIPTION
**Pull request by ocrossi**
…tionEvents

### CODE REVIEW

**Comment by ocrossi** [comment]
@finetjul clean PR

**Comment by finetjul** [comment]
LGTM.

Please note that the ShapeWidget example is broken (not due to your fix though)

**Comment by finetjul** [comment]
@agirault

**Comment by ocrossi** [comment]
after more testing some problems emerge from this hotfix. I'm adding a WIP tag to the PR and dig further

**Comment by agirault** [comment]
Hi @ocrossi! What's the reason for not propagating those events?

**Comment by ocrossi** [comment]
The reason would be to force the placePoint functions to only place points and to leave the interaction propagation part to the handleLeftButtonPress and handleLeftButtonRelease. This comes from a case where you want to place a widget with a set of coordinates without having the user interacting with it.

**Comment by finetjul** [comment]
> This comes from a case where you want to place a widget with a set of coordinates without having the user interacting with it.

said differently, Octave does not want to trigger * Interaction events when points are placed programmatically.

**Comment by floryst** [comment]
If the event handlers (`*Press` and `*Release`) handle emitting interaction events, then this looks good to me.

**Comment by agirault** [comment]
Understood thank you @ocrossi and @finetjul. That's good information to have: could you add that explanation to the commit message?

**Pull request merged**
