### PR TITLE
feat(PaintFilter): improve and factorize PaintFilter's labelMap modification methods

### PR DESCRIPTION
**Pull request by boucaud**
While deriving a class from vtkPaintFilter to add new operations, users can not access the history variable, which stops them from being able to use undo/redo functionality in their new operations.

This exposes the filter's history to child classes.

### CODE REVIEW

**Comment by boucaud** [comment]
@finetjul

**Comment by finetjul** [comment]
LGTM
@floryst  WDYT?

**Comment by floryst** [comment]
LGTM, since it can be useful. I assume this involves new operations that operate on the history and do more than just basic undo/redo? I ask since subclasses that are only interested in basic undo/redo still have access to the undo/redo methods.

**Comment by boucaud** [comment]
> I assume this involves new operations that operate on the history and do more than just basic undo/redo?

Indeed. To be more specific, these functions don't use the filter's worker/workerPromise (no startStroke/endStroke). They set a new labelMap as a result, and compute the diff between new and old labelMap to append to the history.

**Comment by boucaud** [comment]
Reverted the previous changes, factorized mask operation, history  handling, added a new method to directly change the labelMap.

@finetjul @floryst WDYT ?

**Comment by finetjul** [comment]
LGTM

**Comment by floryst** [comment]
LGTM

**Pull request merged**
