### PR TITLE
Paint widget

### PR DESCRIPTION
**Pull request by floryst**
Adds a PaintWidget and a PaintFilter.

- There are commits in this PR that fix bugs in ScalarsToRGBA and OpenGLImageMapper

### CODE REVIEW

**Comment by jourdain** [comment]
What is the status there? Is it ready to merge?

**Comment by floryst** [comment]
Not yet. I'm sort of using this as scratch space, but as of now I just need to move the PaintFilter to it's own directory before this is ready to merge.

**Comment by jourdain** [comment]
is it good now?

**Comment by floryst** [comment]
Yep

**Pull request merged**
