### PR TITLE
add vtkSkybox class and fix depth comparison issue

### PR DESCRIPTION
**Pull request by martinken**
also add ability to render a texture from another
node without having it be in the scene graph.

### CODE REVIEW

**Comment by jourdain** [comment]
It seems we are missing the skybox files...

**Comment by martinken** [comment]
working as intended ;-)

**Comment by martinken** [comment]
Do: merge

**Comment by jourdain** [comment]
Sorry... The robot took some time to decode your `Do: merge` and click on the green button. ;-)

**Comment by martinken** [comment]
Fricking lazy robots ;-)

**Pull request merged**
