### PR TITLE
perf: drawArrays getParameter cache

### PR DESCRIPTION
**Pull request by FezVrasta**
### Context
Same as my other PR but for the drawArrays function.

### Changes

- [ ] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**: 

### Funding
This contribution is funded by [Sirona Medical](https://sironamedical.com).

### CODE REVIEW

**Comment by finetjul** [comment]
This does not seem cachable, I feel that DEPTH_WRITEMASK can have a varying value depending on the calling context.

@martinken

**Comment by martinken** [comment]
Would require that all calls to get it go through that method for it to be safe in vtk.js  Otherwise some other class in vtk.js could change the state and the helper would not know it I think.

**Comment by floryst** [comment]
@martinken @finetjul I've updated this PR to properly cache all calls to `gl.depthMask()`.

Aside: I personally think using a Proxy over the WebGLContext object would be better for implementing the cache. Since I think we still technically have IE11 support (at least until we drop webgl1), this is implemented as an added API to vtkOpenGLRenderWindow.

**Comment by finetjul** [comment]
Please consider our discussions on #2146 and more specifically [that](https://github.com/Kitware/vtk-js/pull/2146#issuecomment-956466172) comment.

It seems that Option 1 does not work (due to performance issues), so we have to do Option 2, i.e. proxy WebGLContext by caching all calls to GL.

Who volunteers ? @FezVrasta ?

**Comment by floryst** [comment]
I think we can reasonably drop IE11 at this point, so let's go with the Proxy approach.

**Comment by floryst** [comment]
Closing this in favor of #2507, since I can't push to Federico's branch for some reason. (It worked before...)

**Pull request closed without merging**
