### PR TITLE
perf(Rendering): add high res render as needed, multitouch

### PR DESCRIPTION
**Pull request by martinken**
This topic adds a final high res render after animation had ended.
It also uses the animation logic for multitouch movements.

### CODE REVIEW

**Comment by jourdain** [comment]
Since you are in the event code section, do you want to handle the zoom by "scroll"?
I've added some code to capture those events, they just need to trigger the proper events, I'm guessing...

**Comment by martinken** [comment]
OK added wheelies

**Comment by jourdain** [comment]
thanks

**Comment by jourdain** [comment]
This is SO BEAUTIFUL @martinken !

Works perfectly on my iPod... The only issue is that on my laptop I can not trigger the LOD, I'm always full resolution at full speed... ;-)

**Pull request merged**
