### PR TITLE
feat(Interaction): add mouse position for scroll

### PR DESCRIPTION
**Pull request by boucaud**
Adds a way to use the ZoomToMouseManipulator with the scroll wheel.

### CODE REVIEW

**Comment by boucaud** [comment]
@jourdain @finetjul

**Comment by jourdain** [comment]
`feat(InteractorStyleManipulator): add mouse position for scroll`

**Comment by jourdain** [comment]
LGTM

**Comment by boucaud** [comment]
I just rebased, seems like there is an error with the latest commit, don't merge.

**Comment by boucaud** [comment]
This can be merged after https://github.com/Kitware/vtk-js/pull/1348

**Pull request merged**
