### PR TITLE
fix(ProxyManager): Reject promise on save/load error

### PR DESCRIPTION
**Pull request by floryst**
Errors that occur inside the promise should be handled accordingly.

### CODE REVIEW

**Comment by jourdain** [comment]
LGTM, the formatting was hard to read

**Comment by floryst** [comment]
Yeah, formatting is a wonky thing for this. Just adds `catch(reject)` to the end of each `Promise.all()`.

**Comment by jourdain** [comment]
yes I managed to extract that... ;-)

**Comment by jourdain** [comment]
The good thing is that glance will have the touch support along with your fix.

**Pull request merged**
