### PR TITLE
test(RenderWindow): Test adding then removing renderer

### PR DESCRIPTION
**Pull request by scottwittenburg**

### CODE REVIEW

**Comment by scottwittenburg** [comment]
@martinken Here is a test that exercises the issue I asked about earlier today.  Since it's a test involving webgl, the test must be run locally to see the failure.

**Comment by scottwittenburg** [comment]
@jourdain Can you take a look when you get a chance?

**Comment by jourdain** [comment]
Need to add the resource management. See other tests for examples. Otherwise looks good.

**Comment by scottwittenburg** [comment]
@jourdain Ok, hopefully all set now.

**Comment by jourdain** [comment]
Can I merge it?

**Comment by scottwittenburg** [comment]
@jourdain Sorry I should have added a note when I closed this.  Based on Ken's email earlier today, it seems we should not expect the screen to be cleared when we remove a renderer.  Hence my next PR (#224) providing a custom updater for vtkRenderWindow.

**Comment by jourdain** [comment]
Are you saying that test is invalid and should not be merged?

**Comment by scottwittenburg** [comment]
Yes I'm saying that.

**Comment by jourdain** [comment]
ok then I delete the branch then. thx

**Pull request closed without merging**
