### PR TITLE
fix(examples): use ESM package in examples

### PR DESCRIPTION
**Pull request by daker**
### Context

The recommended package is the ESM package but the UMD packages is used in all examples, this PR will allow all the examples to switch to ESM package.

### Results

All the examples should build fine and use the ESM package `@kitware/vtk.js`

### Changes

- [ ] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

**Comment by jourdain** [comment]
Did you try to run `npm run example -- SimpleCone` just to validate that the example runner was fine with the code change along with `npm run doc:www` for the website generation?

**Comment by daker** [comment]
Yes i have tried to launch some examples and they work without errors and for the `doc:www` command, the webpack part is build successfully but fails at launching Chrome since i don't use it.

**Comment by floryst** [comment]
`Documentation/config.js` also needs the alias, as that file defines the webpack config for building the examples.

**Comment by jourdain** [comment]
Yes the iframe as an issue when running locally but if you go to the full example it should work.

**Comment by daker** [comment]
@floryst I have made the changes, the `Examples/Applications` are building and working

**Comment by floryst** [comment]
Sounds good! I'll test it one more time and if it's good, I'll go ahead and merge.

**Comment by floryst** [comment]
LGTM, thanks!!!

**Pull request merged**
