### PR TITLE
fix(vtkvolumemapper): fix the bounds of the volume.

### PR DESCRIPTION
**Pull request by gandis0713**
Modify the comparing condition for direction of the plane that sets the bound s of the volume.

### CODE REVIEW

**Comment by daker** [comment]
@gandis0713 did you had a chance to look at #1687 ?

**Comment by gandis0713** [comment]
@daker  Yes, I modified after seeing #1687.

**Comment by martinken** [comment]
looks good as our convention is that positive values are kept and negative are discarded.  +1

**Comment by daker** [comment]
@gandis0713 the yarn.lock needs to be removed from PR

**Comment by PaulHax** [comment]
I tried out the branch. This clips the same direction:
```
mapper.addClippingPlane(clipPlane1);
mapperSurface.addClippingPlane(clipPlane1);
```
Thanks for the follow through gandis.

**Comment by gandis0713** [comment]
@daker Thank you for the notice. I removed yarn.lock.

**Pull request merged**
