### PR TITLE
fix(landmarkTransform): Fix the call of constants that doesn't exist

### PR DESCRIPTION
**Pull request by laurennlam**
Bad call of one of a mode

### CODE REVIEW

**Comment by jourdain** [comment]
Let's wait for your fix on the exposition of constants. Just keep pushing to the same topic. There is no need to create a new version each time unless you think it is worth it.

**Comment by laurennlam** [comment]
The merge can wait. I'll add the feature you told me. But it seems to have some issues with glmatrix. I'll push all commits at the same time when all will be fixed. Thanks !

**Comment by jourdain** [comment]
You can push everything as separate commits. We will just merge when everything is ready.

**Comment by laurennlam** [comment]
@jourdain , I just discovered that the version of gl-matrix I used in vtkLandmarkTransform wasn't the same as the current one in package.json. May I change it from 2.3.1 to 2.3.2 ? Or would you prefer to me to update the code to fit with 2.3.1 ? Thanks.

**Comment by jourdain** [comment]
We carefully picked that version for some reason. So you should use that version otherwise you may break some other code.

**Comment by laurennlam** [comment]
ok. Thanks ! I'll update the code.

**Comment by laurennlam** [comment]
All seems to be ok.

**Comment by jourdain** [comment]
Do you know that because you made a feat(), you will move vtk version from 2.12.0 to 2.13.0

**Comment by laurennlam** [comment]
No I didn't know...
I'll make a new pull request.

**Comment by jourdain** [comment]
Not that it matters, but I wanted you to be aware... Look at https://github.com/semantic-release/semantic-release for more understanding.

**Pull request closed without merging**
