### PR TITLE
fix(abstractMapper): typescript definition file updated, gl-matrix imported

### LINKED ISSUE #2032: AbstractMapper typescript definition file ;missing import
### Environment
- **vtk.js**: 
- **OS**: 
- **Browser**:

### PR DESCRIPTION
**Pull request by lambacini**
Abstractmapper TypeScript definitions were updated . gl-matrix imported.

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [ ] Run `npm run reformat` to have correctly formatted code

### Context
fix #2032

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### Testing

- [x] This change adds or fixes unit tests
- [x] All tests complete without errors on the following environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**: 

_This contribution is funded by [Example](https://example.com)._

### CODE REVIEW

**Comment by jourdain** [comment]
What do you think @daker ?

**Comment by daker** [comment]
@lambacini You just need to rebase your branch then it's ready to be merged

**Comment by lambacini** [comment]
Is there anything I can do for the faulty check?  Should I close pr and open it again?

**Comment by daker** [comment]
Thanks @lambacini fixes has been made in PR #2040, we can close this one.

**Pull request closed without merging**
