### PR TITLE
Add cell notion and some derivated class (triangle, line)

### PR DESCRIPTION
**Pull request by laurennlam**
The previous pull request of vtkMath has to be merge before launching tests of triangle and line because they use the modification.

### CODE REVIEW

**Comment by jourdain** [comment]
I'm guessing the code is coming from the C++ side of VTK ?

**Comment by laurennlam** [comment]
You're right.

**Comment by jourdain** [comment]
Do you know why the tests are failing?

**Comment by jourdain** [comment]
Once green should we merge it?

**Comment by laurennlam** [comment]
Because it uses determinant2x2 from vtkMath with 4 arguments. Now the R of vtkMath has been merge, I'll be rebased on master and then it should be green.

**Comment by jourdain** [comment]
Feel free to clean the determinant2x2 in that PR if you feel like it. Thanks!

**Comment by jourdain** [comment]
Let me know if you want me to merge it... Or if you want to push more stuff to it.

**Comment by laurennlam** [comment]
@jourdain I'm implementing the cell picker and I saw that vtkCell can be improved. So I'll warn you when you can merge it. Thanks

**Comment by laurennlam** [comment]
@jourdain you can merge it. Normally, all usefull method have been implemented.
Thanks

**Comment by jourdain** [comment]
Can you merge/rebase the two PR that you would like me to push to master into a single one?
I'm not saying to squash the commits, just keep the same set of commits but just inside a single PR.
That way only one new version will be made. Specially if they depend on one another.

Thanks!

**Comment by laurennlam** [comment]
@jourdain No problem. I'll also merge the PR for the Picker and the pickFromList which is missing.

**Comment by laurennlam** [comment]
This PR has been merge into one in 'Add Cell picker and cell notion'

**Pull request closed without merging**
