### PR TITLE
chore(Rendering): Remove some OpenGL Dependencies

### PR DESCRIPTION
**Pull request by martinken**
Start removing places where people explicitly used
OpenGL so that the code can be more rendering API
agnostic.

Also fix one test that was not releasing its resources.

### CODE REVIEW

**Comment by martinken** [comment]
@floryst @jourdain  this passes the tests, but... I'm not sure how much the widgets are tested in the base tests or if these changes will impact glance etc. So please take a look.

**Comment by jourdain** [comment]
At a first glance that looks reasonable... But a true widget validation should be performed.

**Comment by jourdain** [comment]
Some examples are currently broken because of an update method name?

`const openGLRenderWindow = fullScreenRenderer.getOpenGLRenderWindow();`

**Comment by martinken** [comment]
Yes from a prior commit, but I'll update this one to fix it for those two examples.

**Comment by martinken** [comment]
@jourdain can you take a look at how I changed testCategoricalColors.js  I want to change all the tests but wanted to run it by you first.

**Comment by jourdain** [comment]
Your change to `testCategoricalColors.js` looks fine to me. Maybe put the import `import 'vtk.js/Sources/Rendering/Misc/RenderingAPIs';` inside the root test.js file instead. So one location for all the tests...

**Comment by martinken** [comment]
I might move it there in the future. As I will likely move some tests in OpenGL to RenderingCore in the future as well. I haven;t gotten to the point of trying to really run the tests on WebGPU but when I do I'll probably do another round of cleanup.

**Comment by martinken** [comment]
Manually ran and played with five of the widget examples and they seemed to work. So merging. If someone runs into an issue let me know. If needed we can add a widget.getOpenGLRenderWindow method for backwards compatibility that just returns the apiSpecificWindow, if there are external codes that require it and don't want to update.

**Pull request merged**
