### PR TITLE
feat(vtkhttpsceneloader): import additional volumeProperty values

### PR DESCRIPTION
**Pull request by boucaud**
Import more properties, color transfer functions and opacity piecewise functions

Paraview scene before export:
DeepinScreenshot_select-area_20201215140805

vtk-js after import:
DeepinScreenshot_select-area_20201215140853

### CODE REVIEW

**Comment by boucaud** [comment]
@finetjul @jourdain please review.

**Comment by finetjul** [comment]
That looks good to me (high-level review)

**Review by jourdain — APPROVED** [review]
LGTM

**Pull request merged**
