### PR TITLE
Add create cube from raw in open gl texture

### PR DESCRIPTION
**Pull request by laurennlam**

### CODE REVIEW

**Comment by jourdain** [comment]
@laurennlam is ready to merge or is it WIP? @martinken should be the one to review since it is on the GL side...

**Comment by laurennlam** [comment]
It should be ready to merge.

**Comment by martinken** [comment]
+2  looks good to me

at some  point it would be nice to have a test/example that uses a cube map texture.

**Comment by laurennlam** [comment]
@martinken I keep in mind the test example. Thanks !

**Pull request merged**
