### PR TITLE
fix(STLReader): add ascii support

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by agirault** [comment]
FYI, I think the stl reader already existed in itk.js (@thewtex)

**Comment by jourdain** [comment]
That's weird, because anything that itk list as supported file, we simply expose and use.

**Comment by jourdain** [comment]
But I don't think vtk.js has a mapping between ITK/mesh and VTK/mesh, we only have an Image handler. That could be the reason too...

**Comment by thewtex** [comment]
Added an issue here for a bridge to itk.js mesh file formats:

  https://github.com/Kitware/vtk-js/issues/789

**Pull request merged**
