### PR TITLE
refactor(reslicecursor): rename reslice cursor view types

### PR DESCRIPTION
**Pull request by finetjul**
Remove medical meaning to variable names.

BREAKING CHANGE: Rename of ViewTypes

### CODE REVIEW

**Comment by finetjul** [comment]
@laurennlam

**Comment by laurennlam** [comment]
LGTM

**Comment by finetjul** [comment]
@floryst @jourdain can be merged whenever (no rush, it is a style change) you want to increase major version

**Comment by floryst** [comment]
Sounds good. I'll wait for my update-deps branch to be finalized. Is the line widget PR also a breaking change?

**Comment by finetjul** [comment]
@floryst yes, 6e384bef9ae10d8cafb41863486ef121557734b8 is also breaking change.

Line Widget MR is not polished yet but I think it can be merged. We will further improve it in a different MR

**Comment by floryst** [comment]
I'm testing a `next-major` branch , so I'm changing this PR's merge target to `next-major` so we can collate all of the PRs that have breaking changes.

**Pull request merged**
