### PR TITLE
ci(npm): Use npm ci instead of npm install

### PR DESCRIPTION
**Pull request by thewtex**
This is the preferred command for deployment that uses
package-lock.json.

### CODE REVIEW

**Comment by thewtex** [comment]
Resemble.js 3.1.0 released this fix:

https://github.com/rsmbl/Resemble.js/pull/168

so we can update it in vtk.js -- it also updates the canvas dependency, which fixes installation issues.

**Comment by jourdain** [comment]
@thewtex can you pull from master and update the lock file in order to fix the conflict?

**Comment by jourdain** [comment]
did via side commits

**Comment by thewtex** [comment]
Thanks, @jourdain

**Pull request closed without merging**
