### PR TITLE
Fix typescript

### PR DESCRIPTION
**Pull request by zweideux**
### Changes

- [ ] Documentation and TypeScript definitions were updated to match those changes

### Testing

- [ ] This change adds or fixes unit tests
- [ ] All tests complete without errors on the following environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**: 

_This contribution is funded by [Example](https://example.com)._

### CODE REVIEW

**Comment by floryst** [comment]
Looks good. Thanks!

**Comment by floryst** [comment]
Oh, please rebase and follow [semantic-release](https://github.com/semantic-release/semantic-release) commit messages. These changes can be considered a `doc()` change.

**Comment by jourdain** [comment]
I guess we are just waiting for commit rename and rebase.

**Comment by floryst** [comment]
This looks good to merge. After checks are green, I will merge.

**Pull request merged**
