### PR TITLE
Refactor WebXR Rendering to `vtkWebXRRenderWindowHelper`

### PR DESCRIPTION
**Pull request by tbirdso**
### Context

Under previous experimentation WebXR rendering support was fully contained within the `vtkOpenGLRenderWindow`. This refactoring encapsulates that support in the new class `vtkWebXRRenderWindowHelper`. That class accepts a reference to an underlying render window and is responsible for driving XR operations.

Refactoring allows for better separation of concepts and could enable XR rendering with alternate rendering backends other than `vtkOpenGLRenderWindow` in the future.

### Results

No feature changes. XR methods are removed from the `vtkOpenGLRenderWindow` interface. An application aiming to use WebXR with vtk.js must now instantiate a `vtkWebXRRenderWindowHelper` to drive XR behavior.

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes
- [x] Added `vtkWebXRRenderWindowHelper`
- [x] Removed XR interface from `vtkOpenGLRenderWindow`

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [x] Tested environment:
  - **vtk.js**:  `master`
  - **OS**:  Windows 10
  - **Browser**:  Chrome 117.0.0.0

### Additional Notes

Additional effort may be required for refactoring WebXR interaction handling.

### CODE REVIEW

**Comment by tbirdso** [comment]
@floryst ping for review

**Review by floryst — APPROVED** [review]
LGTM!

**Comment by floryst** [comment]
Since this is a breaking change, we will merge it along with the rest of v29 PRs.

**Comment by tbirdso** [comment]
@floryst There is interest in making this available in a VTK.js release sooner rather than later. @aylward made the point this morning that breaking changes are limited to XR users, anyone who was previously using `vtkOpenGLRenderWindow` without XR will not notice behavioral changes.

Would you be open to merging this today? Or, when do you expect v29 to release?

**Comment by floryst** [comment]
I'll start work to cut a v29 release today.

**Pull request merged**
