### PR TITLE
perf(Texture): Only scale cube texture to power of two when not WebGL2

### PR DESCRIPTION
**Pull request by thewtex**
Co-authored-by: Ken Martin <ken.martin@kitware.com>

### CODE REVIEW

**Comment by thewtex** [comment]
This saves about 0.14 sec on load.

**Comment by thewtex** [comment]
CC: @martinken @jourdain @agirault

**Comment by martinken** [comment]
+1 Thanks!

**Comment by thewtex** [comment]
@jourdain can this please have some merge love? :heart_eyes_cat:

**Comment by jourdain** [comment]
Sure, can I bundle them with others?

**Comment by thewtex** [comment]
Yes

**Comment by agirault** [comment]
@martinken @thewtex could this be called here also?
https://github.com/Kitware/vtk-js/pull/594/files#diff-80916a397e2ba7d72b3769b22d96fcecL678

Or instead - if we should always skip for gl2 - could we return the input right away if that's the case to avoid forgetting that check in the future?

Seems like I'm getting a lot of slowliness because of this.

**Comment by martinken** [comment]
Yes,  we should skip for WebGL2 there as well.

**Comment by agirault** [comment]
thanks, i'll make a patch.

**Pull request merged**
