### PR TITLE
Fix min value

### PR DESCRIPTION
**Pull request by felixveysseyre**

### CODE REVIEW

**Comment by felixveysseyre** [comment]
@jourdain I am asking myself another question, why is it better to use `Number.MAX_VALUE` rather than `Infinity` constant ?

**Comment by martinken** [comment]
+1

**Comment by felixveysseyre** [comment]
Also, I did not replaced `Number.MAX_VALUE` in `distanceToLine` and `intersectWithLine` functions as it seemed correct to me.

Can somebody can confirm me that ?

**Comment by felixveysseyre** [comment]
@jourdain

- `distanceToLine`: `vtk-js/Sources/Common/DataModel/Line/index.js`, line 12
- `intersectWithLine`: `vtk-js/Sources/Common/DataModel/Line/index.js`, line 136

**Comment by jourdain** [comment]
I think it would be nice to change them so we don't get tempted to wrongly used `Number.MIN_VALUE`, but based on the way the code is written that value is not actually used.

**Pull request merged**
