### PR TITLE
ResliceCursorWidget: Fix jump

### PR DESCRIPTION
**Pull request by finetjul**
With very particular dataset, in very particular condition, scrolling axial was making the coronal view "jump" slices. 

Closes #1746

### CODE REVIEW

**Comment by finetjul** [comment]
@laurennlam

**Comment by laurennlam** [comment]
+1 Thanks for deeper investigations.

**Comment by laurennlam** [comment]
Did you check if the test passed ?

**Comment by finetjul** [comment]
> Did you check if the test passed ?

CI says it's all good. I just merged. Thanks for the review.

**Pull request merged**
