### PR TITLE
style(types): maintain consistent formatting

### PR DESCRIPTION
**Pull request by floryst**
### Context
The typescript files are not formatted via prettier, potentially resulting in some inconsistent formatting across files.

### Results
Typescript files are reformatted in accordance to prettier. The formatting is now consistent with the javascript ifles.

These changes were generated via `npm run reformat`, after updating that command to include typescript files.

### Changes
- [x] formatted typescript files

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
N/A

### CODE REVIEW

**Review by finetjul — APPROVED** [review]
LGTM

**Comment by daker** [comment]
I remember someone sharing a config file for this, maybe @bruyeret or @boucaud ?

**Comment by bruyeret** [comment]
I don't remember sharing a tsconfig for vtk.js, do you @bourdaisj ?

**Comment by floryst** [comment]
I don't recall tsconfig supporting formatting options. In any case, keeping prettier as a single source of formatting truth is simpler.

**Review by daker — COMMENTED** [review]
LGTM

**Pull request merged**
