### PR TITLE
 feat(ZoomManipulator): Configurable zoom in/out direction 

### PR DESCRIPTION
**Pull request by mix3d**
Allows consumers to reverse the in/out up/down directions when using the ZoomManipulator

Our other image viewer is in the reverse direction. This would allow us to make our app's interfaces congruent.

### CODE REVIEW

**Comment by mix3d** [comment]
@jourdain @martinken thoughts? Is my variable name ok?

**Comment by finetjul** [comment]
LGTM

**Comment by finetjul** [comment]
Commit title should probably be more something like that:
`feat(ZoomManipulator): Flip zoom in/out direction`

 - feature is the general name of the modified feature
 - Adds ->Add

**Comment by jourdain** [comment]
LGTM too, sorry for the slow response. Agree with @finetjul for the commit message. It just make nicer changelog...

**Comment by jourdain** [comment]
Where are we on that PR?

**Comment by mix3d** [comment]
Got lost in the shuffle. I'll try to get the commit reworded and forcepushed back. Might have to rebase at this point. We'll see.

**Comment by mix3d** [comment]
@jourdain all set!

**Pull request merged**
