### PR TITLE
chore(ImageMapper): Add sliders in the example (brightness)

### PR DESCRIPTION
**Pull request by laurennlam**
Add sliders in the example to change level and window of slices

### CODE REVIEW

**Comment by laurennlam** [comment]
@jourdain I click on PR before seing that there's conflicts. Sorry. I think I forgot to pull the master branch...

**Comment by jourdain** [comment]
@laurennlam you need to rebase since I moved your example in `vtk-js/Examples/Volume/MultiSliceImageMapper/index.js`

**Comment by jourdain** [comment]
as it was conflicting with the ImageMapper example in Rendering/Core

**Comment by jourdain** [comment]
The conflict reason is because all examples are gathered in the same directory so you can not have two example with the same name...

**Comment by laurennlam** [comment]
@jourdain thanks. I'll change it.

**Pull request closed without merging**
