### PR TITLE
feat(WidgetManager): remove all widgets

### PR DESCRIPTION
**Pull request by wtchnm**

### CODE REVIEW

**Comment by wtchnm** [comment]
@finetjul

**Comment by finetjul** [comment]
Can you please factorize with `removeWidget` ? 
I would prefer to not duplicate the code.

**Comment by wtchnm** [comment]
I would prefer it too, but I found "ghost widgets" because of [getInteractor().render()](https://github.com/Kitware/vtk-js/blob/73f828a2a840a680801389d82335ce22ad45c772/Sources/Widgets/Core/WidgetManager/index.js#L416) and [onRenderEvent(updateSvg)](https://github.com/Kitware/vtk-js/blob/73f828a2a840a680801389d82335ce22ad45c772/Sources/Widgets/Core/WidgetManager/index.js#L298). If you want, I can provide a reproducible repo.

**Comment by finetjul** [comment]
I'm not sure to understand the relationship between factorization and "ghost widgets".

Wouldn't something like following work:
```
publicAPI.removeWidgets() {
 model.widgets.forEach();
 model.widgets = []
 ...
 publicAPI.onWidgetRemoved();
}

publicAPI.removeWidgetInternal(widget) {
 removeActor()
 removeFromSVGLayer()
}

publicAPI.removeWidget(widget) {
 ...
 publicAPI.removeWidgetInternal(widget)
 ...
 publicAPI.onWidgetRemoved();
}

publicAPI.onWidgetRemoved() {
  ...render()
  enablePicking();
}
```

**Comment by wtchnm** [comment]
Sorry, I thought you were suggesting that I loop through the widgets and use the existing method.
The example that you gave me worked well.

**Comment by finetjul** [comment]
LGTM

**Comment by finetjul** [comment]
thanks !

**Pull request merged**
