### PR TITLE
fix(SynchronizableRenderWindow): add type annotations

### PR DESCRIPTION
**Pull request by yasushi-saito**
Add typescript definitions for SynchronizableRenderWindow.

Minor fix & tightening of type definitions for RenderWindow & ImageStream

### CODE REVIEW

**Comment by jourdain** [comment]
LGTM

**Comment by daker** [comment]
@jourdain is `viewId` a string or number? if it's a string then this should be fixed, right?

https://github.com/Kitware/vtk-js/blob/758989ee8d01fbe61a27b14973d1e83f4ec7f572/Sources/IO/Core/ImageStream/DefaultProtocol.d.ts#L6-L7

**Comment by jourdain** [comment]
It is a string that is computed from a number. "1"

**Comment by yasushi-saito** [comment]
Ok, changed all `viewId: number` to `viewId: string`.

**Comment by jourdain** [comment]
@floryst I will let you merge it when you want to bundle it with other vtk.js changes.

**Pull request merged**
