### PR TITLE
docs(ts): Add and update TypeScript definitions

### PR DESCRIPTION
**Pull request by boucaud**
Adds definitions for ViewStream, RemoteView, fixes definitions for WSLinkClient

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### Testing

- [ ] This change adds or fixes unit tests
- [ ] All tests complete without errors on the following environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**: 

_This contribution is funded by [Example](https://example.com)._

### CODE REVIEW

**Comment by boucaud** [comment]
@finetjul please review

**Comment by finetjul** [comment]
@daker

**Comment by finetjul** [comment]
@daker can you please review ?

**Comment by daker** [comment]
@finetjul i already reviewed it, i don't see any new commit.

**Comment by daker** [comment]
@finetjul i already reviewed it, i don't see any new commit.

**Comment by finetjul** [comment]
@daker Gotcha. Thanks. There is no new commit, I just did not see that you reviewed it. 
Please add a message like "LGTM" or something like that when you review a PR.

**Comment by daker** [comment]
i will wait for @boucaud to update the PR according to the messages.

**Comment by finetjul** [comment]
@daker we do not see messages, are you sure you "submitted" your review ?

**Review by daker — CHANGES_REQUESTED** [review]

**Comment by daker** [comment]
@finetjul Ok my bad, i didn't submit the review, it should be ok now

**Comment by daker** [comment]
@finetjul LGTM, it still needs a rebase.

**Pull request merged**
