### PR TITLE
fix(ImageMapper): label outlines with I/J slicing

### PR DESCRIPTION
**Pull request by floryst**
### Context
#3135 

### Results
Using `setUseLabelOutline(true)` with the ImageMapper will now work with the other slicing modes.

### Changes

- [ ] vtkImageMapper shader changed to support I/J slicing modes with label outline

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**: 

I'll add tests later. Just wanted to get this out first.

### CODE REVIEW

**Comment by PaulHax** [comment]
This fixes outline rendering in VolView PR: https://github.com/Kitware/VolView/pull/670

**Comment by finetjul** [comment]
@sedghi

**Review by finetjul — APPROVED** [review]
LGTM but I prefer @sedghi to review

**Review by sedghi — APPROVED** [review]
I think it makes sense, can we just make sure the original data also works now?

**Comment by floryst** [comment]
> I think it makes sense, can we just make sure the original data also works now?

Which original data? The existing tests pass, and I'll adapt tests from @PaulHax for I and J slicing.

**Comment by floryst** [comment]
I've added I+J slicing tests.

**Pull request merged**
