### PR TITLE
docs(breaking_changes): document that Node 10 support has been droppe…

### PR DESCRIPTION
**Pull request by finetjul**
…d in 19.3.0

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Context
It was not documented that node 10 is no longer supported.

### Changes
- [x] Documentation and TypeScript definitions were updated to match those changes

### Testing
- [ ] This change adds or fixes unit tests
- [x] All tests complete without errors on the following environment:
  - **vtk.js**: master -->
  - **OS**: Windows 10
  - **Browser**: Chrome

### CODE REVIEW

**Comment by daker** [comment]
@floryst don't you think that adding a `.nvmrc` file would be a good idea for that?

**Comment by floryst** [comment]
I like that idea. vtk.js targets the LTS versions (maintenance + active), so we can specify that for folks who use nvm. (Assuming they remember to run `nvm use`.)

@finetjul if you also think it's a good idea, then it'll be good to run `echo 'lts/*' > .nvmrc` and add that to this PR.

**Comment by finetjul** [comment]
@floryst I have no idea what nvmrc is for but I trust you. I added the file like requested

**Comment by daker** [comment]
@finetjul nvm is a version manager for node.js, it allows you to use multiple node.js installation on a same system, and .nvmrc is file that will tell nvm what node version the project is using.

On the other side, i am not sure why your .nvmrc is a binary file, it should be a text file.

https://github.com/nvm-sh/nvm#nvmrc

**Comment by finetjul** [comment]
@daker gotcha, thanks for the explanation

file was detected as binary because it was UTF-16. I converted it to UTF-8

**Comment by floryst** [comment]
LGTM

**Pull request merged**
