### PR TITLE
fix(WebGL): hint the high preference GPU

### LINKED ISSUE #2205: Run VTK.js on dedicated GPU?
I have a laptop with Intel **i7 cpu and nvidia RTX2080 gpu**, when I run any vtkjs example it happened to be running on the internal gpu instead of my NVIDIA card, I found a fix which is to control rendering options from control panel and it worked! 
**My question: Is there a way that my context choose the high performance gpu and use it by dafault?**

### PR DESCRIPTION
**Pull request by daker**
### Context

Hint the high preference GPU to the browser

Be aware that on certain OS+Browser combination you can **never** set high performance and the browser will use the integrated GPU.

https://bugs.chromium.org/p/chromium/issues/detail?id=681341#c81

fix #2205
### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

**Comment by daker** [comment]
@martinken can you take a look?

**Review by floryst — COMMENTED** [review]
LGTM

**Comment by martinken** [comment]
@floryst  any idea what the CI issue is?

**Comment by floryst** [comment]
Sometimes one of the browsers fails to connect to karma. I don't know if it's a config issue, or an upstream issue. We may increase the reconnect timeout.

**Pull request merged**
