### PR TITLE
Rename macro.js to macros.js

### PR DESCRIPTION
**Pull request by floryst**
### Context

- As per the discussion in #1990, this patch renames macro.js to macros.js, and keeps a macro.js around for backwards compatibility with downstream users.

### Changes

- Fix all usages of `macro.js` to use `macros.js`
- [x] Documentation and TypeScript definitions were updated to match those changes

### Results

Downstream consumers of vtk.js should no longer have issues with babel-plugin-macros eating our macro.js.

### Testing

- [ ] This change adds or fixes unit tests
- [x] All tests complete without errors on the following environment:
  - **vtk.js**: v18.6.0

### CODE REVIEW

**Comment by floryst** [comment]
FYI @FezVrasta @WillCMcC

**Comment by agirault** [comment]
@jourdain

**Comment by jourdain** [comment]
Sorry for the late review. But since it involve fixing all the macro(->s) import. Should we merge macro into `Sources/vtk` and make sure we only use named import/export for the pieces we want from vtk/macro?

Or do we have some cycle dependency import issue? 

That way we have little risk of conflict down the road. 

Since it is a breaking change, I'm wondering if we are better off moving away from macro altogether. 

I'm not saying we should, but I wanted us to think about that as well... What do you think?

**Comment by floryst** [comment]
Merging into `Sources/vtk` is an option, but not necessary to get around the issue. This is not a breaking change from a user perspective, because I generate `macro.js` from `macros.js` at package time. It's only a "breaking change" from someone working on vtk.js, and I don't think that should be considered a breaking change (since the purpose of such designations is to notify the user that the API has changed).

Existing (external) users of `macro.js` will not be impacted by this change. The users who are impacted by the babel-plugin-macros situation will now be able to use `macros.js` instead. `macro.js` is kept around for backwards compatibility.

What do you think?

**Comment by jourdain** [comment]
I see, it make sense. All good with me. Thanks for keeping it backward compatible.

**Review by jourdain — APPROVED** [review]

**Pull request merged**
