### PR TITLE
Image Outlining Filter for labelmaps

### PR DESCRIPTION
**Pull request by katiamar63**
The code is an outcome of NA-MIC Project Week 31 (https://github.com/NA-MIC/ProjectWeek). Filter creates labelmap outline in a given direction (Slicing Mode). This is a vtk.js version of existing 3D slicer functionality.

### CODE REVIEW

**Comment by jourdain** [comment]
We will need to rewrite the history to properly format the commit messages.

**Comment by katiamar63** [comment]
Thanks for info.

pt., 28 cze 2019 o 14:14 Sebastien Jourdain <notifications@github.com>
napisał(a):

**Comment by floryst** [comment]
Did a quick pass, and this looks good to me. As Seb mentioned, the commits should be formatted appropriately (check out the commit history or lookup "semantic-release" if you're not familiar with it).

**Comment by katiamar63** [comment]
Hi Forrest,
Should I do this commit message formatting as it was not clear to me from
Seb post ?

śr., 24 lip 2019 o 13:58 Forrest Li <notifications@github.com> napisał(a):

**Comment by floryst** [comment]
Yeah we need the commit messages to be formatted as per [semantic-release](https://github.com/semantic-release/semantic-release) because that helps us auto-generate changelogs and dictates which semantic version component to update.

**Comment by katiamar63** [comment]
Forrest, Maybe we could [squash in Github](https://github.blog/2016-04-01-squash-your-commits/) all my commits from PR into 1 commit with the following message:
`feat(ImageOutlineFilter): Add vtkImageOutlineFilter. `
I suppose I can't do it since I do not have rights.

**Comment by jourdain** [comment]
Replaced by https://github.com/Kitware/vtk-js/pull/1162

**Pull request closed without merging**
