### PR TITLE
feat(PaintWidget): Add a rectangle widget and an ellipse widget.

### PR DESCRIPTION
**Pull request by RemiCecchinato**

### CODE REVIEW

**Comment by RemiCecchinato** [comment]
@finetjul

**Comment by RemiCecchinato** [comment]
@finetjul @luciemac

**Comment by finetjul** [comment]
Hi @floryst, can you please have a look ?

**Comment by finetjul** [comment]
👍

**Comment by luciemac** [comment]
:+1:

**Comment by floryst** [comment]
Nice! Tried out your branch and I quite like the ellipse and rectangle paints.

A few things I noticed:
- After drawing with the ellipse, what looks to be a green circle handle shows up at the bottom left corner of the image.
- On a fresh reload, if you use the paintWidget and draw an "L" in the lower left hand corner right outside of the image, it fills the entire image with paint. Not sure if this existed before or if it's a regression. An animation is provided below for context.

paint-widget-new-bug-2019-07-02

Once those get addressed, I think it looks good.

**Comment by RemiCecchinato** [comment]
> Nice! Tried out your branch and I quite like the ellipse and rectangle paints.
> 
> A few things I noticed:
> 
>     * After drawing with the ellipse, what looks to be a green circle handle shows up at the bottom left corner of the image.
> 
>     * On a fresh reload, if you use the paintWidget and draw an "L" in the lower left hand corner right outside of the image, it fills the entire image with paint. Not sure if this existed before or if it's a regression. An animation is provided below for context.
> 
> 
> paint-widget-new-bug-2019-07-02
> 
> Once those get addressed, I think it looks good.

Thanks @floryst for pointing theses bugs to me. They should be fixed now.

**Pull request merged**
