### PR TITLE
fix(GeometryRepresentationProxy): setOpacity typedef param type

### PR DESCRIPTION
**Pull request by jadh4v**
### Context
Fix setOpacity() and getOpacity() param and return types.
Also fixed some indentation and ordering of function declarations.

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [x] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

**Comment by jadh4v** [comment]
Some of these changes are related to replacing tabs with spaces.

**Review by daker — APPROVED** [review]
LGTM

**Comment by finetjul** [comment]
@daker aren't tabs (instead of spaces) supposed to be used in VTK.js typescript files ?

**Comment by daker** [comment]
> daker aren't tabs (instead of spaces) supposed to be used in VTK.js typescript files ?

Yes you are right, i didn't saw his comment, this reminds of https://github.com/Kitware/vtk-js/pull/2459#issuecomment-1209395137

> Some of these changes are related to replacing tabs with spaces.

@jadh4v would you mind putting tabs instead ?

**Review by finetjul — CHANGES_REQUESTED** [review]
index.d.ts must have tabs

**Comment by jadh4v** [comment]
Got it. Thanks for catching that.

**Review by finetjul — APPROVED** [review]
LGTM

**Pull request merged**
