### PR TITLE
Obj texture reader

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by jourdain** [comment]
@martinken the current code as an issue with the texture coordinates as they have value bigger than one.

Maybe we can synch up tomorrow so you could explain me how I should rescale them based on the MTL data. Unless, you just want to go ahead and fix the issue yourself.

**Comment by jourdain** [comment]
Unless the file is not fully correct?

```
vt -0.526200 0.698500
vt -0.530000 0.698500
vt -0.530000 0.548700
vt -0.526200 0.548700
vt -0.466300 0.548700
vt -0.470000 0.548700
vt -0.466300 0.698500
vt -0.470000 0.698500
vt -0.474500 0.698500
vt -0.521700 0.698500
vt -66.929100 198.818893
vt -8.661400 41.338600
vt 0.000000 41.338600
vt 0.000000 198.818893
vt -17.322800 0.000000
vt -49.606300 0.000000
vt -58.267700 41.338600
vt -66.929100 41.338600
vt -0.482800 0.737800
vt -0.513500 0.737800
```

**Comment by jourdain** [comment]
```
[.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
0.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]GL ERROR :GL_INVALID_OPERATION : glGenerateMipmap: Can not generate mips
2310.0.0.0/:1 [.Offscreen-For-WebGL-0x7fd5ab827000]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.
```

**Comment by martinken** [comment]
Texture coordinates greater than one are fine. The issue is using a non power of two texture with unallowable filtering options or mipmapping. Make sure mipmapping is off and they are set to clamp, not repeat.  I probably need to add code to autorescale to POT when the user requests mipmap or repeat with a NPOT texture.

**Comment by jourdain** [comment]
Ok? Is there anything that we can do?

**Comment by jourdain** [comment]
@martinken , I've forced push and rebased on master.

**Pull request merged**
