### PR TITLE
perf: use Set to power class hierarchy

### PR DESCRIPTION
**Pull request by FezVrasta**
### Context

The custom ClassHierarchy class is effectively re-implementing the `Set` object. Using `Set` can result in better performance, especially when it doesn't get transpiled. The existing ClassHierarchy when transpiled results in many GC events.

### Results

No GC events and a cleaner interface.

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

**Comment by finetjul** [comment]
I guess it is fine to me (except for the broken dashboard). 

Please consider the following discussion for in-depth usage and limitations:
https://github.com/Kitware/vtk-js/pull/1913

**Comment by FezVrasta** [comment]
I can't see what test is failing, they all report a [PASS] status 🤔

**Comment by finetjul** [comment]
That means there is a hang. I just re-started the test.

**Comment by FezVrasta** [comment]
It failed again, it works fine locally, I also tested this change on our app and it looks okay.

**Comment by floryst** [comment]
Test failures: I wonder if chrome 116 specifically is being finicky in github CI.

GC: that will be resolved generally #2901.

Using Set: I am mostly fine with moving to Set. I do consider it a micro-optimization since class hierarchies are never long enough for perf to matter. This will result in a breaking change, since downstream consumers who make their own vtk.js classes will need to switch to using `model.classHierarchy.add`. If you agree, please add such to the commit message.

**Comment by FezVrasta** [comment]
I'm okay in waiting for #2901 to see how the performance is affected, in general I thought it would make to use a Set here as it's what the code is after.

**Comment by jourdain** [comment]
Make sure the `const a = obj.getState()` and `vtk(a)` still works...

**Comment by FezVrasta** [comment]
I tested out the new version and the memory issue is not there anymore, thanks

**Pull request closed without merging**
