### PR TITLE
fix(BoundingBox): Correct initialization of bounds

### PR DESCRIPTION
**Pull request by laurennlam**

### CODE REVIEW

**Comment by jourdain** [comment]
That is wrong you want the initial bounds to be something that you can grow. Not something that is so big that it will never grow.

**Comment by laurennlam** [comment]
Got it ! I thought it has to be max value it could.

**Comment by jourdain** [comment]
The point is also to start with an invalid bound that we can check too.

**Comment by laurennlam** [comment]
Thanks for the explanations @jourdain

**Pull request closed without merging**
