### PR TITLE
fix(ForwardPass): Render layered renderers in correct order

### PR DESCRIPTION
**Pull request by zmanvortex**
Modified ForwardPass to render layered renderers in correct order.

Rendering order was always based on the order that renderers were added to the renderwindow regardless of the layer number setting of the renderer. Modified ForwardPass to render by layer number order.

### CODE REVIEW

**Comment by jourdain** [comment]
Could you rename your commit as follow so the generated change log will be easier to follow.

`fix(ForwardPass): Render layered renderers in correct order`

Also the tests seems to fail. Did you run them locally by calling `npm run test`?

**Comment by jourdain** [comment]
There is 2 issue to fix in the code

```
/home/vsts/work/1/s/Sources/Rendering/OpenGL/ForwardPass/index.js
35:28  error  Expected '===' and instead saw '=='
57:17  error  Replace `fbSize·===·null·||·fbSize[0]·!==·size[0]·||·fbSize[1]·!==·size[1]` with `⏎··············fbSize·===·null·||⏎··············fbSize[0]·!==·size[0]·||⏎··············fbSize[1]·!==·size[1]⏎············`  prettier/prettier
   
```

You can fix one of them by calling `npm run reformat` then for the other one you need to replace your `==` by `===`.

**Comment by zmanvortex** [comment]
When running 

> npm run test

It just hangs on 

> Chrome 74.0.3729 (Windows 10.0.0) LOG: 'ok 642 vtkOpenGLVolumeMapper Lighting'.
I had to set the following in karma.conf:

> captureTimeout: 210000,
> browserDisconnectTolerance: 3, 
> browserNoActivityTimeout: 600000,
> browserDisconnectTimeout: 600000,
otherwise it would error on timeout after 30000ms. Any ideas?
I have corrected the errors that you mentioned and am not sure if I should issue another pull request. I am confused whether it will create a duplicate pull request from this one?

**Comment by jourdain** [comment]
Just force push to the current one (branch). That will retrigger the tests and we should be fine. You need to amend your commit with the correct text.

**Comment by jourdain** [comment]
Can you squash those commits so only one appear?

**Comment by jourdain** [comment]
Otherwise we will have 2 change log entry.

**Comment by zmanvortex** [comment]
I had to push another branch after amending the commit name to the correct format.

**Comment by jourdain** [comment]
thx!

**Pull request merged**
