### PR TITLE
Fix picker examples

### LINKED ISSUE #709: Picker demos are not working
PointPicker and CellPicker examples are not working on your demo pages.  I attach screenshots from FF v.59.0.2 and Chrome 65.0.x
pointpicker2
pointpicker

### PR DESCRIPTION
**Pull request by agirault**
Fix #709 #545
- [x] Update API in point picker example to vtk.js 6+
- [x] Cleanup picker examples
- [ ] Properly handle `PickPosition`: reset? do not expose? (discussion below)
- [x] Fix `PickedPositions` by taking [`scaling`](https://github.com/kitware/vtk-js/commit/a8179e7) into account

cc: @laurennlam @thewtex

### CODE REVIEW

**Comment by agirault** [comment]
@laurennlam could you clarify what is the difference between `pickPosition` and `pickedPositions` ?

**Comment by jourdain** [comment]
It is still named WIP

**Comment by agirault** [comment]
Was waiting to see if I could get a quick answer from Laurenn.
@laurennlam when you have a chance feel free to restart the discussion here. That `pickPosition` is a source of confusion.

**Comment by laurennlam** [comment]
I can't take a look on this for now. But as I remember, I just "copy/paste" the c++ vtk source file.

**Pull request merged**
