### PR TITLE
Fix example

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by jourdain** [comment]
@laurennlam The path to the data is wrong. `Data` only exist on your local file system but not on the github.io endpoint. If you look any example that load data they all use the lower case path.

**Comment by laurennlam** [comment]
@jourdain Okay thanks !

**Comment by jourdain** [comment]
@laurennlam is there any setting that can be adjust to make the slice less bright? Just so we can get a better viz.
Maybe add a slider to control the `brightness` like the drag interaction you have here: https://kitware.github.io/vtk-js/examples/ImageMapper.html

Thanks!

**Comment by laurennlam** [comment]
Sure

**Comment by jourdain** [comment]
thx

**Pull request merged**
