### PR TITLE
fix(scalarbaractor): check for renderable mtime when deciding if we should update the actor

### PR DESCRIPTION
**Pull request by Julesdevops**
### Context
Say you have a `scalarBarActor` instance and you want to sometimes update its styling; doing something like that:
```js
const newOverlayColor = "green";
scalarBarActor.setAxisTextStyle({ fontColor: newOverlayColor });
scalarBarActor.setTickTextStyle({ fontColor: newOverlayColor });
renderWindow.render();
```
Currently this code does not work.

### Results
This PR makes it so any changes done using the `vtkScalarBarActor` public API triggers a redraw of the actor.

### Changes
Check for the renderable modified time.
- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
- [ ] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: v19.4.0
  - **OS**: Archlinux
  - **Browser**: Firefox 100.0 (64-bit)

### CODE REVIEW

**Comment by Julesdevops** [comment]
thanks @luciemac

**Comment by Julesdevops** [comment]
@finetjul What's your opinion on this?

**Comment by finetjul** [comment]
I do not know enough the scalar bar actor to validate the PR.
Maybe @martinken has an idea ?

**Comment by martinken** [comment]
Should be fine. +1

**Pull request merged**
