### PR TITLE
feat(WebGPU): improve volume rendering with WebGPU

### PR DESCRIPTION
**Pull request by martinken**
Includes a variety of fixes for texture management on
WebGPU including handling many more types of textures
than before. The simple 8 bit volume rendering example
now works on WebGPU.

Performance and generality and features are all still
to come.

### CODE REVIEW

**Comment by martinken** [comment]
@jourdain has something changed in our formatting? Checking my logs locally I see
```
["INFO" - 4:01:18 PM] Formatting file:///c%3A/Users/ken.martin/Documents/vtkjs/vtk-js/Sources/Rendering/WebGPU/VolumePassFSQ/index.js
["INFO" - 4:01:18 PM] Using config file at 'c:\Users\ken.martin\Documents\vtkjs\vtk-js\prettier.config.js'
["INFO" - 4:01:18 PM] Using ignore file (if present) at c:\Users\ken.martin\Documents\vtkjs\vtk-js\.prettierignore
["INFO" - 4:01:18 PM] File Info:
{
  "ignored": false,
  "inferredParser": "babel"
}
["INFO" - 4:01:18 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 4:01:18 PM] Prettier Options:
{
  "filepath": "c:\\Users\\ken.martin\\Documents\\vtkjs\\vtk-js\\Sources\\Rendering\\WebGPU\\VolumePassFSQ\\index.js",
  "parser": "babel",
  "useTabs": false,
  "tabWidth": 2,
  "endOfLine": "lf",
  "printWidth": 80,
  "singleQuote": true,
  "trailingComma": "es5",
  "arrowParens": "always"
}
["INFO" - 4:01:18 PM] Formatting completed in 0.075ms.
```

Yet CI is complaining

**Comment by martinken** [comment]
with 
```
["INFO" - 3:16:05 PM] Extension Name: esbenp.prettier-vscode.
["INFO" - 3:16:05 PM] Extension Version: 9.0.0.
```

**Comment by martinken** [comment]
And it is reformatting. Just not the way CI wants it oddly enough.

**Comment by jourdain** [comment]
Just run `npm run reformat`

**Comment by jourdain** [comment]
Also @floryst just merge some update... You probably need to run `npm install` to update your dev environment.

**Comment by martinken** [comment]
My node and npm were old (3 years old) so I think I had a lot of stuff getting out of date and something changed. Updated it all and the formatting matches now.

**Pull request merged**
