### PR TITLE
fix(tubefilter): fix incorrectly sized output array in TubeFilter

### PR DESCRIPTION
**Pull request by jbeezley**
When drawing multiple lines, the output array is too small.  This causes segments to be missing from the scene.

A minimal example is
```js
const lines = vtk({
  vtkClass: 'vtkPolyData',
  points: { 
    vtkClass: 'vtkPoints',
    dataType: 'Float32Array',
    numberOfComponents: 3,
    values: [ 
      0,0,0,
      1,1,0,
      1,1,1,
      0,1,1,
    ] 
  },
  lines: { 
    vtkClass: 'vtkCellArray',
    dataType: 'Uint16Array',
    values: [ 
      2, 0, 2,
      2, 1, 3,
    ],
  },
});

const tubeFilter = vtkTubeFilter.newInstance({numberOfSides: 3, capping: false, sidesShareVertices: false});
tubeFilter.setInputData(lines);
```
where the second line is missing on current master.

Not sure, but this could be related to #848 as well.

### CODE REVIEW

**Comment by jbeezley** [comment]
Actually, now that I look at this more, it still isn't correct when lines have varying number of points.

**Comment by daker** [comment]
Is this related to #1546 ?

**Comment by jbeezley** [comment]
Indeed it is.

**Comment by jbeezley** [comment]
The logic is more complicated than I originally thought.  In the latest version, I'm calculating the output array size that is consistent with how it is being used in `generatePoints`.  I don't have great insight in how precisely the code works, but playing around with this version appears to fix the issue.

**Comment by jourdain** [comment]
You could use dynamic arrays and just convert them at the end

**Comment by jbeezley** [comment]
There could be a significant performance hit from not preallocating the arrays.  Also, since I don't completely understand the code, I would rather avoid making more changes than necessary.

**Comment by jourdain** [comment]
You can also slightly over allocate and make a view at the end. (In case that help to handle the "unknown part")

**Comment by jourdain** [comment]
@jbeezley Are you good with your changes? Should we merge it?

**Comment by jbeezley** [comment]
Yes, I'm happy with it.

**Pull request merged**
