### PR TITLE
ITKHelper itk-wasm compatibility fixes

### PR DESCRIPTION
**Pull request by weeeina**
### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Context
See description in issue: https://github.com/Kitware/vtk-js/issues/2162

### Changes

- remove itkImage.direction.data since it is an array instead of object
- add ITKPixelTypes lookup so that switch statement is not always default case

### Results

ITKHelper now successfully loads .nii files when used in following way:
```
const niftiReader = vtkITKImageReader.newInstance();
    niftiReader.setFileName('image.nii');

    niftiReader
      .parseAsArrayBuffer(res)
      .then(() => {
        const source = niftiReader.getOutputData();
        return source;
      })
      .then((source) => {
        ...
 ```

### Testing

- [ ] This change adds or fixes unit tests
- [x] All tests complete without errors on the following environment:
- vtk.js: 17.17.2
- itk-wasm: ^1.0.0-a.8
- OS: iOS 11.3.1
- Browser: Chrome 95.0.4638.69

### CODE REVIEW

**Review by thewtex — CHANGES_REQUESTED** [review]
@weeeina thank you for the contribution! :pray: 

A few improvements will result keep the code working that has not yet migrated and result in the desired behavior:

Near the top of the function, we should detect whether the `itkImage` is an `itk.js` `Image` or an `itk-wasm` `Image`.

This can look something like:

```
// Is this an itk.js Image or an itk-wasm Image?
const bool isITKWasm = itkImage.direction.data === undefined
```

then,

```
if (isITKWasm) {
  itkImage.direction[idx + col * itkImage.imageType.dimension];
} else {
   itkImage.direction[idx + col * itkImage.imageType.dimension];
}
```

To address the pixel type detection, rename `const ITKPixelTypes = {` to `const ITKJSPixelTypes = {`, and also define `const ITKWASMPixelTypes = {`. These were changed to descriptive values to provide a more explicit description when serialized. See:

https://github.com/InsightSoftwareConsortium/itk-wasm/blob/master/src/core/PixelTypes.ts

Then, something like this may work (needs to be tested):

```
const ITKPixelTypes = isITKWasm ? ITKWASMPixelTypes : ITKJSPixelTypes
```

**Comment by weeeina** [comment]
@thewtex Thanks for the tips! I have made the changes to detect whether we are dealing with and itk or itk-wasm image in the convertVtkToItkImage function. However, there's also the convertItkToVtkImage function, so I've kept that as the ITKJSPixelTypes unless there is a way we would like to give the user a choice and/or move to the WASM version on that as well. Can you confirm whether it's okay that it goes itk.js OR itk-wasm --> vtk but vtk --> itk.js _only_?

**Comment by thewtex** [comment]
@weeeina thanks for the updates!

We will also have to update vtk -> itk-wasm in addition to itk-wasm -> vtk, either in this PR or another.

**Comment by weeeina** [comment]
> @weeeina thanks for the updates!
> 
> We will also have to update vtk -> itk-wasm in addition to itk-wasm -> vtk, either in this PR or another.

Thanks @thewtex! I'll leave the vtk --> itk-wasm to another PR, as I'm not entirely clear on how you would be able to differentiate based on what version of itk is being used by the user... 

I noticed that I messed up my first commit message and so the commitlint was not happy with that. Other than that, is there anything I need to do to get this ready for merge?

**Comment by thewtex** [comment]
@weeeina thanks for the update!

I rebased on `master` to address the commit message issues.

Looks good to me!

**Review by thewtex — APPROVED** [review]

**Comment by mhalle** [comment]
I think this patch isn't quite right yet. If using WASM, you want to do   
`switch (ITKPixelTypes[itkImage.imageType.pixelType]) {   // aliased to ITKWASMPixelTypes`
if using JS, you want to do:
`switch (itkImage.imageType.pixelType) {   // an integer `

**Pull request merged**
