### PR TITLE
Fix class hierarchy

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by jourdain** [comment]
@martinken make sure you follow that pattern next time.

**Comment by aronhelser** [comment]
How about a test to illustrate the problem? :)

**Comment by jourdain** [comment]
Good luck with that.

**Comment by jourdain** [comment]
You will have to test each class individually.

For the multi `macro.obj` that does not create any issue just useless creation of methods that get garbage collected.

**Pull request merged**
