### PR TITLE
WIP: test(SphereMapper): Expose scalar coloring issue

### PR DESCRIPTION
**Pull request by scottwittenburg**
Show that we cannot currently disable scalar coloring on the sphere mapper

### CODE REVIEW

**Comment by scottwittenburg** [comment]
I must have hosed something up here, it doesn't seem like my new test was actually run.  I'm looking into it now...

**Comment by scottwittenburg** [comment]
Ah, nevermind, it didn't get run because it's a webgl test.  But it fails locally for me just fine :smile:

**Comment by jourdain** [comment]
@martinken that branch add a test which highlight a bug. Do you mind fixing the issue in that mapper and merging it? It might be something simple as a missing modified() or mtime tracking.

**Comment by martinken** [comment]
Fixed by https://github.com/Kitware/vtk-js/pull/367

**Comment by jourdain** [comment]
@scottwittenburg can you try to rebase on master, test and merge it? 
Specially since Ken has fixed it.

Thanks!

**Pull request merged**
