### PR TITLE
fix: 🐛 Fix parallel projection rendering using the VolumeMapper

### PR DESCRIPTION
**Pull request by JamesAPetts**
Fix the setCameraShaderParameters function of the VolumeMapper.

Adds tests and examples also.

Closes: #843

### CODE REVIEW

**Comment by JamesAPetts** [comment]
@martinken  here is the fix for #843. The projection back onto the vc plane was incorrect for parallel projections for the VolumeMapper.

As with all these things it was a painstakingly difficult task to find this one line fix: https://github.com/Kitware/vtk-js/blob/fc914d3d75d5b6d67a26797cfa2a96ece2abea93/Sources/Rendering/OpenGL/VolumeMapper/index.js#L454

The rest of the PR is test cases, as its quite important this keeps working going forwards :).

P.S. @swederik  and I _think_ this is the correct solution, but feel free to push back/correct us if you think that `t` should be something else.

**Comment by JamesAPetts** [comment]
Example in `react-vtkjs-viewport` addressing some of the issues in #843 :

https://media.giphy.com/media/KztKRqcEraorVHt1gE/giphy.gif

**Comment by martinken** [comment]
Yes! I think you found the culprit which is the hard part. Can you try something? What about directly using pos for parallel projection. If my mathing is working I think that is the fix.  It expands the bounds out a tad farther I think. Something like this

```
    for (let i = 0; i < 8; ++i) {
      vec3.set(
        pos,
        bounds[i % 2],
        bounds[2 + (Math.floor(i / 2) % 2)],
        bounds[4 + Math.floor(i / 4)]
      );
      vec3.transformMat4(pos, pos, model.modelToView);
      if (!cam.getParallelProjection()) {
        vec3.normalize(dir, pos);

        // now find the projection of this point onto a
        // nearZ distance plane. Since the camera is at 0,0,0
        // in VC the ray is just t*pos and
        // t is -nearZ/dir.z
        // intersection becomes pos.x/pos.z
        const t = -crange[0] / pos[2];
        vec3.scale(pos, dir, t);
      }
      // now convert to DC
      vec3.transformMat4(pos, pos, keyMats.vcdc);

      dcxmin = Math.min(pos[0], dcxmin);
      dcxmax = Math.max(pos[0], dcxmax);
      dcymin = Math.min(pos[1], dcymin);
      dcymax = Math.max(pos[1], dcymax);
    }
```

**Comment by JamesAPetts** [comment]
Let me give it a shot, thanks!

**Comment by JamesAPetts** [comment]
That makes a lot more sense, and is a lot easier to read. Works great, let me just update the image for the karma tests :).

**Comment by JamesAPetts** [comment]
@martinken Updated the method to your suggestion and also the subtly different test image 👍 .

**Comment by martinken** [comment]
Thanks @JamesAPetts

**Comment by JamesAPetts** [comment]
And thanks for the speedy review @martinken !

**Pull request merged**
