### PR TITLE
fix(ArrowHandleRepresentation): do not zero out Z

### PR DESCRIPTION
**Pull request by floryst**
### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Context
- LineWidget example fails to have oriented handles when using a non-default plane manipulator normal.

### Changes
- [ ] remove code that zeros out the Z component of an orientation vector

### Results
- oriented handles work properly in the LineWidget example

### CODE REVIEW

**Comment by floryst** [comment]
@finetjul just checking in with you: this looked like a debugging statement of some sort that got left in. Removing it allows orientation to work regardless of the plane manipulator's orientation.

**Comment by finetjul** [comment]
From what I remember, this code is not a bug nor a debugging statement, it was there to enforce the arrow to always "face" the camera.

**Comment by floryst** [comment]
Oh, I see now. Seems like there is a separate issue causing the handle orientations to not properly line up. Here is a sample where the plane normal is along Y and the camera is looking along Y:

image

**Comment by floryst** [comment]
I'm moving this to an issue.

**Pull request closed without merging**
