### PR TITLE
vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters errors

### PR DESCRIPTION
**Pull request by PaulHax**
### Context

When calling the static mapper `vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters`, there is an error because the "class" does not have a publicAPI  with a `modified()` function.

### Results

Does not error now when calling `vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters`.  

Some other tests are failing after adding the test in this PR.  Seems that calling `setResolveCoincidentTopologyPolygonOffsetParameters` with the initial results of `getResolveCoincidentTopologyPolygonOffsetParameters` does not completely undo the effect?
image

### Changes

The error fix involved adding a noOp `modified` function.  Alternatives could be to check if `publicAPI` has `modified` in macros.js or upgrade the Mapper static object with macros.js' `function obj(publicAPI = {}, model = {})` "constructor."   

### PR and Code Checklist

- [ ] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [ ] Run `npm run reformat` to have correctly formatted code

### Testing

- [x] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

**Comment by PaulHax** [comment]
I guess the open questions/todos on this is issue PR:

- [ ] Do we want to keep supporting the `vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters` function?  We are using it in VolView: https://github.com/Kitware/VolView/blob/main/src/main.js#L34
- [ ] Is this "fix" by adding the noOp `modified` function acceptable?
- [ ] How to test `vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters` without affecting other tests?

**Comment by finetjul** [comment]
> Do we want to keep supporting the vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters function? We are using it in VolView: https://github.com/Kitware/VolView/blob/main/src/main.js#L34

I think so, there is also a Static ResolveCoincidentTopology in VTK C++.

**Review by finetjul — COMMENTED** [review]
Shouldn't you expose a "static" MTime ? so that it can be considered when deciding to building/updating the shader ?

**Comment by PaulHax** [comment]
> Shouldn't you expose a "static" MTime ? so that it can be considered when deciding to building/updating the shader ?

I think that makes sense as the global/static factor/offset are added with instance values as a uniform for the mappers shaders.  How to do that?  Upgrade the static object to be a full `macros.obj`, then each mapper registers a `onModified` for the static object and updates its own `MTime` when the static object changes?

>  How to test vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters without affecting other tests?

Do you have any insight on that?

**Comment by finetjul** [comment]
> I think that makes sense as the global/static factor/offset are added with instance values as a uniform for the mappers shaders. How to do that? Upgrade the static object to be a full macros.obj, then each mapper registers a onModified for the static object and updates its own MTime when the static object changes?

Yes, that makes sense

**Comment by finetjul** [comment]
>>How to test vtkMapper.setResolveCoincidentTopologyPolygonOffsetParameters without affecting other tests?
> Do you have any insight on that?

I'm not sure what the issue is TBH

**Comment by PaulHax** [comment]
superseded by https://github.com/Kitware/vtk-js/pull/3142

**Comment by PaulHax** [comment]
Can't reopen this PR so opening #3143

**Pull request closed without merging**
