### PR TITLE
perf: substitute

### PR DESCRIPTION
**Pull request by FezVrasta**
### Context

this new implementation is 40-60% faster (depending if the `all` flag is set to true or not)

https://jsbench.me/kil8a6dx31/1

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [x] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**: 

### Funding
This contribution is funded by [Sirona Medical](https://sironamedical.com).

### CODE REVIEW

**Comment by finetjul** [comment]
Can you please avoid nested ternary operators and maybe create a test to make sure there is no regresion.

**Comment by FezVrasta** [comment]
I added some tests but I'm not sure how to run them, `npm run test` doesn't seem to catch them

**Comment by floryst** [comment]
> I added some tests but I'm not sure how to run them, `npm run test` doesn't seem to catch them

The tests should be picked up by karma via `npm run test`. I think you need to call `t.end()` after all of your assertions, or use `t.plan(numOfAssertions)`.

**Comment by finetjul** [comment]
LGTM

**Comment by FezVrasta** [comment]
Everything should be okay now

**Pull request merged**
