### PR TITLE
Add cell picker and cell notion

### PR DESCRIPTION
**Pull request by laurennlam**
Implement cell picker which use vtkCell and particulary vtkTriangle.
The cellPicker can only pick triangles for now because other kind of cells are not implemented.
An example if the cell picker have been added : press shift key + click

### CODE REVIEW

**Comment by jourdain** [comment]
I'm guessing that's the one you want me to merge?

Is there anything you want specific review on?

**Comment by laurennlam** [comment]
Yes, that's the one.
Maybe a review in the cell picker could be nice. I skip most of things and I don't know if I made it in the right way. But it seems to work so if you don't have time, I think it's not a problem to merge it.

**Comment by jourdain** [comment]
@martinken do you want to review it? Or can I merge it and then we can always fix it later if need be. ;-)

**Comment by martinken** [comment]
Merge it and we can address issues as they pop up. Having these classes is a ***lot*** better than nothing so definitely merge :-)

**Pull request merged**
