### PR TITLE
Improve the contribution process

### PR DESCRIPTION
**Pull request by brianhelba**
* docs: Update and unify contribution docs

### CODE REVIEW

**Comment by brianhelba** [comment]
@jourdain PTAL and review.

If this is acceptable, should you merge or should I?

**Comment by brianhelba** [comment]
Actually, please wait, I want to ensure that the `package-lock.json` doesn't contain an issue.

**Comment by jourdain** [comment]
Don't worry, I just tried some fix that was good to merge to see what the changelog looked like. But based on what I said, I need to update kw-websuite. Test again and only them merge all your contribution. That way the BREAKING_CHANGE will include the updated toolchain.

**Comment by jourdain** [comment]
Love the contribution but `package.json` and its lock file should not be part of that.

**Comment by jourdain** [comment]
Please remove the package.json + lock so we can merge the documentation part.

**Comment by brianhelba** [comment]
@jourdain I've rebased this and updated it to include only the doc changes.

Sorry, this fell off my radar for a while.

**Pull request merged**
