### PR TITLE
Update kw web suite and dependencies

### PR DESCRIPTION
**Pull request by floryst**
This updates dependencies and kw-web-suite.
- Reformat code to fit with new eslint and prettier versions
- Update css-loader options to be in-line with latest version

FYI @aneeshikmat @thewtex I'm closing #1305 in favor of this PR, since there are a lot more changes that need to be made when bumping the css-loader version. Thanks for making that PR, and I've attributed you to the relevant commit.

Builds are currently failing. Will investigate...

### CODE REVIEW

**Comment by aneeshikmat** [comment]
Thank you @floryst  for follow, and make these updates and changes! :+1:

**Comment by thewtex** [comment]
@floryst thanks!

**Comment by floryst** [comment]
@thewtex Switching from Azure Pipelines to Github Actions

**Comment by thewtex** [comment]
@floryst nice! :green_heart:

**Pull request merged**
