### PR TITLE
fix(LineWidget): Do not unnecessary refresh view on mouse move

### PR DESCRIPTION
**Pull request by finetjul**
In Manipulate mode, when hovering the render window, the LineWidget could trigger an unnecessary
InteractionEvent and refresh

### CODE REVIEW

**Comment by agirault** [comment]
Nice, thanks!

One thing I wonder, instead of doing:
```js
const enablePoint1Widget = state === State.ONP1;
if (enablePoint1Widget !== model.point1Widget.getEnabled()) {
  model.point1Widget.setEnabled(enablePoint1Widget);
  modified = true;
}
```
it would be nice to do:
```js
modified = modified || model.point1Widget.setEnabled(state === State.ONP1);
```

`AbstractWidget.setEnabled` and `InteractorObserver.setEnabled` already do the check internally not to call `modified()` if nothing changed. We could return `true/false` if it has been modified, my understanding is that it's the convention for `set` methods in VTK and vtk.js. @jourdain could you confirm?

Then, the same thing goes for `setPoint2WorldPosition` and the other methods in `LineRepresentation`, it would be easy too just return the result of the internal `set*` call... but now that I look at it, there are a LOT of calls, so I understand if we don't want to do that for that PR.

**Comment by jourdain** [comment]
Yes the set should return true if something has changed. The macro generated method will do it but it is good practice to do it inside your own methods...

**Comment by finetjul** [comment]
I like your suggestion of having setEnabled returning true/false if modified. 
However there is a risk in setXXX() methods to always perform the check if the new value is truely different from the current value. 
There might be some cases where the check would be too costly (large arrays) or not well defined (precision of the check for floating numbers)...

**Comment by jourdain** [comment]
If costly then go with the "always mark modified" to be on the safe side.

**Comment by finetjul** [comment]
For the costly case, how about adding an extra `force` parameter (default to false). e.g. 
```
setMyParamWithExpensiveCheck(newValue, true); // where true means to "force" the new value without checking
```
For the precision case, how about adding a precision parameter ? e.g.
```
setPoint2WorldPosition(newPos, 0.001); // where 0.001 is the precision used to compare each X,Y and Z values
```

**Comment by jourdain** [comment]
Sure, if it is your own implementation, do what you want. Just know that by convention the set method should `return true`, if the call resulted with a change and false otherwise.

**Comment by agirault** [comment]
Indeed :wink: thanks. I edited my first comment to avoid confusion.

That pr is merged though, I think there is no need to worry too much about using good conventions for the widgets, we plan to do some refactoring when we get some funding for a project that requires widgets: #682

**Pull request merged**
