### PR TITLE
docs(XR): Add discussion on XR emulator

### PR DESCRIPTION
**Pull request by tbirdso**
### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Context

We want to direct developers/users to the WebXR emulator for sampling examples without requiring XR hardware.

Examples are built automatically with `npm example` and do not typically allow room for extra discussion of a given example outside of the source code. This could be a good idea to revisit in the future to allow for extra context around examples. For now, this is a very small change to direct users to the emulator via inline comments.

### Changes

- Inline comments direct users from `Application/SkyboxViewer` and `Geometry/VR` examples to install the WebXR emulator in their browser.

### Results

- Updated documentation.

### Testing

- [x] All tests complete without errors on the following environment:
  - **vtk.js**: v21.3.0
  - **OS**: Windows 10
  - **Browser**: Chrome 96.0.4664.93

_This contribution is funded by [Example](https://example.com)._

### CODE REVIEW

**Comment by tbirdso** [comment]
Further investigation shows that we do in face supply extra information in examples such as ["Geometry Viewer"](https://kitware.github.io/vtk-js/examples/GeometryViewer.html) (see [index.md](https://github.com/Kitware/vtk-js/blob/master/Examples/Applications/GeometryViewer/index.md)). 

I'm not clear from our documentation how to test this locally. Does the build system automatically incorporate `index.md` from the example directory, or are there additional requirements for properly including extra documentation?

**Comment by tbirdso** [comment]
Per @floryst `npm run doc::www` is useful for testing documentation locally

**Comment by tbirdso** [comment]
🤔 

docs-nested

**Comment by floryst** [comment]
Ah, I don't remember if that's an outstanding bug with local docs generation. I will try locally as well.

**Comment by floryst** [comment]
That is a quirk (bug?) of the underlying hexo server, where path rewrites means unnecessary redirects resulting in self-embedded frames. The generated site will be fine. Just click on "Live Example" to test it out.

**Comment by tbirdso** [comment]
Thanks for checking it out @floryst . Should `Geometry/VR/index.md` be included in the page body here? Or am I missing a step somewhere?

**Comment by floryst** [comment]
LGTM. I don't know if we can get the headings to render properly, so this will have to do for now.

**Comment by tbirdso** [comment]
Sorry to add changes after review, just finished drafting a `Development/WebXR Examples` page consolidating WebXR discussion and centralizing examples. @floryst would you mind glancing back over briefly?

xr-examples

**Comment by floryst** [comment]
LGTM to me. I haven't run the actual docs, but the content and screenshots look good.

**Comment by tbirdso** [comment]
Thanks @floryst !

**Comment by tbirdso** [comment]
Squashed and rebased on `master`.

**Pull request merged**
