### PR TITLE
Expose the property's opacity in ImageMapper (1C).

### PR DESCRIPTION
**Pull request by alvarosan**
#304  #714

### CODE REVIEW

**Comment by alvarosan** [comment]
Hey @jourdain @martinken ,  this did the trick for me (needed to do something similar to #304).  Let me know if you have other plans for the implementation, I might be able to finish it up.

**Comment by martinken** [comment]
This looks good to me. +1

**Comment by martinken** [comment]
Are you ready for me to merge this @alvarosan  ?

**Comment by alvarosan** [comment]
Yep, go ahead Ken ;), thanks.

**Pull request merged**
