### PR TITLE
fix(XMLReader): use xml library over builtins

### PR DESCRIPTION
**Pull request by floryst**
### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Context
Should allow usage of XMLReaders in web workers

### Changes

- [x] remove usage of ActiveXObject and DOMParser

### Results
- [x] webworker usage of xml readers should work

### CODE REVIEW

**Comment by finetjul** [comment]
If not built-in, does it mean it will be slower ? if so, should it be optional ?

**Comment by floryst** [comment]
Right now the goal of this PR is to examine the usage of readers in webworkers. DOMParser is not accessible in the webworker scope, and ActiveXObject is IE specific (I don't even know if that proprietary extension made it into Edge).

> If not built-in, does it mean it will be slower ? if so, should it be optional ?

Slower, possibly. Though I don't imagine it being significantly slower for typical usage.

**Comment by floryst** [comment]
I've tested XMLPolyDataReader inside a webworker, and it appears to be working just fine after these changes.

**Review by jourdain — APPROVED** [review]
LGTM

**Comment by finetjul** [comment]
LGTM minus the warning

**Pull request merged**
