### PR TITLE
feat(volume shadow): add volume shadow support for all lighting conditions

### PR DESCRIPTION
**Pull request by JiayiXuu**
### Context
Pull request for adding volume shadow support as part of realistic rendering module, also referred to as secondary shadow ray/secondary scatter. This pull request aligns with recent changes in VTK, but adds optimizations and two extra parameters to further  speed up rendering. Four parameters are included: 
 - `volumetricScatteringBlending`: 
     * range [0.0,1.0]
     * 0.0: surface shadow
     * 1.0: volume/global shadow
 - `globalIlluminationReach`: 
     * range [0.0,1.0]
     * 0.0: maximum volume shadow ray length is equal to 1 unit of sampling distance
     * 1.0: maximum volume shadow ray length is equal to the largest possible value of sqrt(3), i.e. no restriction on shadow ray
 - `volumeShadowSamplingDistFactor`: 
     * range [1.0, Infinity]
     * modifies sampling distance of shadow ray (`SamplingDistanceISVS`) based on sampling distance of primary ray casting (`SamplingDistanceIS`), primarily to increase speed
     * 1.0: `SamplingDistanceISVS` = 1.0 * `SamplingDistanceIS`
     * n: `SamplingDistanceISVS` = n * `SamplingDistanceIS`
 - `anisotropy`: 
     * range (-1.0,1.0)
     * -0.99: light scatters backward
     * 0.99: light scatters forward
     * 0.0: light scatter is isotropic (uniform in all direction)

### Results
**0: Overview**

overview_go_compressed_cropped
_Overview for volume with gradient opacity enabled - this gif is compressed with 2X speed and frame drop_

overview_tf_cropped
_Overview for volume without gradient opacity - this gif has frame drop_

**1: volumetricScatteringBlending**

blending

Surface shadow seems to dominate the rendering result when it is on. So `volumetricScatteringBlending= 1.0` is drastically different from `volumetricScatteringBlending= 0.99`, but `volumetricScatteringBlending = 0.99` is pretty much similar to `volumetricScatteringBlending= 0.0`. I used a biased function so volume shadow is more prominent, though it didn't have a big effect. 

image

**2: volumeShadowSamplingDistFactor**
Shadow ray sampling distance is either equal to or larger than primary ray sampling distance.

samplingDist

Besides the user-specified modification, `SamplingDistanceISVS` is also multiplied by a random number between 0.8 to 1.0 at each sample location. It slightly blurs the "layer effect" when `SamplingDistanceISVS` > `SamplingDistanceIS`. Additionally, it remove the "onion ring" that appears when `globalIlluminationReach = 0.0`. The onion ring appears because vtk.js uses jitter based on a white noise texture with size 32*32, and the same texture is repeated to cover the whole volume. The `random()` function introduced in this PR combine noise texture with another pseudorandom number generator to reduce unnatural artifacts.

image

**3: globalIlluminationReach**

gir

**4: anisotropy**

ezgif com-gif-maker

### Changes

- [ ] Documentation and TypeScript definitions were updated to match those changes - pending
- vtkVolumeFS: add volume shadow support with performance optimization
- OpenGL/VolumeMapper: pass on uniforms to shader
- Core/VolumeMapper: add parameters and range check
- some code clean up

### PR and Code Checklist

- [X] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [X] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: latest master
  - **OS**: Windows 10
  - **Browser**: Chrome 89.0.4389.128

### CODE REVIEW

**Comment by finetjul** [comment]
This seems pretty cool.

Can you please add screenshots to this PR ? 
An interactive basic example (with 4 sliders) would be also very useful.

**Review by daker — CHANGES_REQUESTED** [review]

**Comment by martinken** [comment]
Is the 4 slider example a new example or the same VolumeViewer, I can't seem to find it.

**Comment by JiayiXuu** [comment]
> Is the 4 slider example a new example or the same VolumeViewer, I can't seem to find it.

It's a new example. I'll add that to Volume Example in another commit.

**Review by martinken — APPROVED** [review]
LGTM +1

**Comment by floryst** [comment]
So far so good. Is this still in the draft phase?

**Comment by JiayiXuu** [comment]
> So far so good. Is this still in the draft phase?

Just marked it as ready for review. I'll add the example in another PR.

**Review by floryst — APPROVED** [review]

**Pull request merged**
