### PR TITLE
Fix are matrices equal

### LINKED ISSUE #2324: `areMatricesEqual` is not working
### High-level description
`areMatricesEqual` is not working
The function is just a copy of `areEquals` and is only meant to be used on `number[]` not `number[][]`

### Steps to reproduce

 ```js
vtk.Common.Core.vtkMath.areMatricesEqual([[1,1], [2,2]], [[1,1], [2,2]]) \\ returns false
 ```

### Expected behavior
Function should test equality between matrices and return true if all the values are equals (given an epsilon for floating points).

### Possible fix
```js
export function areMatricesEqual(a, b, eps = 1e-6) {
  if (a.length !== b.length) {
    return false;
  }
  return a.every((line,i) => areEquals(line, b[i], eps));
}
```

### Environment
- **vtk.js**: latest
- **OS**: any
- **Browser**: any

### PR DESCRIPTION
**Pull request by stity**
### Context
- fix #2324 

### Results
Fixes `areMatricesEqual`

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

**Comment by stity** [comment]
> Why do you want to support matrices stored as numbe[][] ? It is not a matrix format supported in VTK.js, is it ?

In `Sources/types.d.ts` you have the following code:
```ts
declare type Matrix = number[][];
```
Is there another type for matrices that would be supported by the current version of `areMatricesEqual` ?

**Comment by daker** [comment]
@finetjul for ex you can see this in `multiplyMatrix` https://github.com/Kitware/vtk-js/blob/83927a18db3a513ef1fcf141491606c32d784841/Sources/Common/Core/Math/index.js#L574

`a` & `b` are two-dimensional arrays
https://github.com/Kitware/vtk-js/blob/83927a18db3a513ef1fcf141491606c32d784841/Sources/Common/Core/Math/index.js#L588

also in other places in the ts def https://github.com/Kitware/vtk-js/blob/41aea103cf66c7823fa6a40d7e2f1b188d15426e/Sources/Common/Core/Math/index.d.ts

I am wrong?

**Comment by jourdain** [comment]
I think you are correct. Those were ported from the c++ as close as we could. But I don't think they are used. On the JS side we prefer to use the gl-matrix helpers. It might be worth trimming down that vtkMath to only expose what we need and remove any code that is coming from C++ but that is not getting used/exercised.

**Comment by daker** [comment]
We had an issue before about this https://github.com/Kitware/vtk-js/issues/2192

**Comment by finetjul** [comment]
For consistency reasons, we should have only 1 way to represent matrices in VTK.js .
For performance reasons, it should be the `number[]` notation and not `number[][]`.

Who wants to convert all those methods (BREAKING_CHANGES !) to take `number[]` instead of `number[][]`?

**Pull request closed without merging**
