### PR TITLE
fix(httpsceneloader): properly handle .vtkjs files with no actor

### LINKED ISSUE #1710: Scene Explorer example not working
When trying out Scene Explorer example to load lidar.vtkjs, nothing is rendered:

image

Upon checking console, the following error can be observed: 

image

Is this a known bug with scene explorer?

### PR DESCRIPTION
**Pull request by boucaud**
fixes #1710

### CODE REVIEW

**Comment by boucaud** [comment]
@jourdain please review

**Comment by jourdain** [comment]
Did that fix the example with the sample vtkjs file provided?

**Comment by jourdain** [comment]
The code change seems reasonable but just looking at the diff, it is not clear what you've done. But if that works now with the old files, then we can merge once green.

**Comment by boucaud** [comment]
> Did that fix the example with the sample vtkjs file provided?

Yes, I tested with lidar.vtkjs and it works.

The issue is with this scene:

```
        {
            "name": "LIDAR data",
            "httpDataSetReader": {
                "url": "0"
            },
            "mapper": {
                "colorByArrayName": "__CustomRGBColorArray__",
                "colorMode": 0,
                "scalarMode": 3
            },
            "property": {
                "representation": 2,
                "pointSize": 2.0,
                "diffuseColor": [
                    1.0,
                    1.0,
                    1.0
                ]
            },
            "type": "httpDataSetReader",
            "lookupTable": {
                "tableRange": [
                    0.0,
                    51.0
                ],
                "hueRange": [
                    0.5,
                    0
                ]
            }
        }
```

Which does not have an actor object.

When adding support for volumes, I checked for item.actor or item.volume when determining which should be created, so in this case no actor would end up being created.

This MR makes it so an actor is created by default, unless item.volume is present.

**Pull request merged**
