### PR TITLE
chore(github): Add PR checklist to PR template

### PR DESCRIPTION
**Pull request by floryst**
Ensure that PRs follow semantic-release and have correctly formatted code.

### Context
- Add housekeeping checklist for ensuring PRs are mergeable.

### Changes
- Updated PR template

### Results
N/A

### Testing
N/A

### CODE REVIEW

**Comment by jourdain** [comment]
+2

**Review by agirault — CHANGES_REQUESTED** [review]
Can we have some bot check that instead automatically? A lot of contributors (including at Kitware) already don't follow the template for doc & testing (see recent PRs merged) but they still get merged.

I'm all for this update, as long as we start enforcing the checklists as requirements to merge.

**Comment by floryst** [comment]
The `npm reformat` should be caught by the build-test step, but I now see that it is not. I will add the validation step.

The check for valid semantic-release commit messages is less clear to me. I will see if I can figure that one out.

In any case, it may still be useful to keep this list around. However, I aim to make the checks more explicit as to what issue has gone wrong.

**Comment by daker** [comment]
@floryst this can be done using git hooks (commitlint + husky)

**Comment by floryst** [comment]
Thanks for the suggestion @daker! I will look into the hooks as well.

**Comment by daker** [comment]
@floryst basicaly, you need to add the following packages to devDeps :

* @commitlint/cli
* @commitlint/config-conventional
* husky

Then add the following to package.json, and of course the rule needs to much what we want:
```json
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ],
    "rules": {
      "subject-case": [
        2,
        "never",
        [
          "start-case",
          "pascal-case"
        ]
      ],
      "scope-case": [
        2,
        "always",
        [
          "lower-case",
          "upper-case"
        ]
      ]
    }
  },
  "husky": {
    "hooks": {
      "pre-commit": "npm run reformat", <- i didn't check if it works
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  },
```

**Comment by floryst** [comment]
Update: @agirault @daker I've made the following changes:
- husky now installs whenever someone git clones vtk.js. Husky is configured to only enforce commitlint. I've opted to not run "reformat" because it's kind of slow for every commit.
- CI now has a new action: PR Checks. This checks for code style as well as commit message lint.
- I've kept the PR template changes because it's still relevant

**Comment by daker** [comment]
+1 from me, it should stop the bleeding

**Comment by floryst** [comment]
This will now be merged, as the checks have been automated. We can refine these as needed, but they work on this PR and I would like to ensure they work on other PRs.

**Pull request merged**
