### PR TITLE
refactor(widgets): remove most of old-style widgets

### PR DESCRIPTION
**Pull request by tomsuchel**
This commit remove most of the old-style widgets (located in Sources/Interaction/Widgets). 2 widgets
(OrientationMarkerWidget and PiecewiseGaussianWidget) have been kept because they are still used in
many other files.

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Context

- re #1961 

### Changes

- All old-style widgets have been deleted except those two:
  - OrientationMarkerWidget
  - PiecewiseGaussianWidget

### Testing

- [ ] This change adds or fixes unit tests
- [x] All tests complete without errors on the following environment:
  - **vtk.js**: v20.0.0
  - **OS**: Ubuntu 20.04
  - **Browser**: Chrome 94.0.4606.71

BREAKING CHANGES: all old-style widgets except OrientationMarkerWidget and PiecewiseGaussianWidget have been removed.

### CODE REVIEW

**Comment by finetjul** [comment]
Please flag it as a breaking change.

**Comment by finetjul** [comment]
@floryst how about we merge it (when it will be ready) into the beta branch ?

**Comment by floryst** [comment]
Merging this into beta will be good. I can update beta as well.

**Comment by floryst** [comment]
Note there are conflicts with this branch.

**Comment by finetjul** [comment]
@tomsuchel to be rebased...

**Comment by floryst** [comment]
What's the status on this? I see BREAKING CHANGE hasn't made it into the commit description.

**Comment by finetjul** [comment]
We have everything ready. I just need to find a bit of time to do the final
merges.

I'll try to do it before the end of the month.

Thanks,
Julien.

Le jeu. 13 janv. 2022, 18:54, Forrest Li ***@***.***> a
écrit :

**Pull request merged**
