### PR TITLE
fix(eslint): no-return-assign error from eslint

### PR DESCRIPTION
**Pull request by jjomier**
eslint is complaining about no-return-assign. Code was changed to pass the error.

BREAKING CHANGE: none

none

### CODE REVIEW

**Comment by jourdain** [comment]
Please change the commit message otherwise you will trigger a major version change (It should not contain `BREAKING CHANGE`. Leave the field empty when you answer the questions).

Moreover, this should just be a style() change so no new version get published.

**Comment by jjomier** [comment]
How to change the commit message?

**Comment by jourdain** [comment]
```
$ git commit --amend
$ git push origin {branch_name} -f
```

And the commit message should just be `styl(eslint): no-return-assign error from eslint`

**Comment by jjomier** [comment]
Thanks! I was wondering if I had to rerun thru commitizen. I'll push it again.

**Comment by jjomier** [comment]
Should be good now.

**Comment by jourdain** [comment]
Commitizen is just a helper to format your commit message. But once you know the syntax, you can skip it all together.

**Comment by jjomier** [comment]
Good to know!

**Pull request merged**
