### PR TITLE
docs(ts): fix TypedArray definition

### PR DESCRIPTION
**Pull request by daker**
### Context

Type `TypedArray` shouldn't include `number[]`

### Changes

- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [ ] This change adds or fixes unit tests 
- [ ] Tested environment:
  - **vtk.js**: 
  - **OS**: 
  - **Browser**:

### CODE REVIEW

**Comment by daker** [comment]
@finetjul

**Comment by finetjul** [comment]
You should probably update MatrixBuilder and vtkDataArray/vtkCellArray accordingly (they all support typed AND non typed arrays)

**Comment by daker** [comment]
i think MatrixBuilder, vtkDataArray and vtkCellArray are already correct, let me know if you see anything wrong

**Comment by finetjul** [comment]
MatrixBuilder.apply() should take in `TypedArray` or `number[]`

vtkDataArray.setData() should take in `TypedArray`  or `number[]`

vtkCellArray.setData() should take in `TypedArray`  or `number[]`

**Review by finetjul — APPROVED** [review]

**Pull request merged**
