### PR TITLE
fix(DynamicFloat32Array): Try to provide replacement for DynamicTypedArray

### PR DESCRIPTION
**Pull request by jourdain**

### CODE REVIEW

**Comment by jourdain** [comment]
@martinken do you think it will better than the current code?

**Comment by jourdain** [comment]
The test seems to pass but I'm not sure that `colorData` is for sure an UInt8Array?

**Comment by jourdain** [comment]
@martinken , I think this looks good and was planning to merge it. Do you agree?

**Comment by martinken** [comment]
Yes colorData should always be Uint8

**Comment by jourdain** [comment]
perfect thanks!

**Pull request merged**
