### PR TITLE
Clean reslice cursor widget

### PR DESCRIPTION
**Pull request by finetjul**
### Context
The goal is to simplify the customization of the Reslice Cursor widget.

### Results
The Reslice Cursor widget is now using low-level widget representations that can be easily customized.

### Changes
- [x] Documentation and TypeScript definitions were updated to match those changes

### PR and Code Checklist
- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing
- [ ] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: master
  - **OS**: Windows 10
  - **Browser**: Chrome

### CODE REVIEW

**Comment by finetjul** [comment]
@floryst ready for merge.

**Comment by floryst** [comment]
LGTM overall!

**Comment by floryst** [comment]
Does this supersede #2579? If so, we can close that one. Also, if this isn't needed asap, I can throw together another breaking change to fully remove SVG widgets.

**Comment by finetjul** [comment]
> Does this supersede https://github.com/Kitware/vtk-js/pull/2579? If so, we can close that one. 

#2579 merges into master, while #2591 merges into beta.

> Also, if this isn't needed asap, I can throw together another breaking change to fully remove SVG widgets.

It can wait until the end of the week :-)

**Comment by floryst** [comment]
Merging this into beta first, and then I will merge my SVG deprecation changes.

**Pull request merged**
