### PR TITLE
Stl writer

### PR DESCRIPTION
**Pull request by thomas-beznik**
Hello everyone,

I have adapted my code for writing binary and ascii STL files to vtk.js. I have troubles to test it properly and have also not succeeded in making an example, additional help there would be welcome!

### CODE REVIEW

**Comment by jourdain** [comment]
Glancing through the code, it seems great.

I noticed 2 small issues:
- You should register your writer into the parent index.js (Sources/IO/Geometry/index.js)
- you need to rework your git history using the commitizen format so proper changelog and version number could be generated. (i.e. `feat(STLWrtiter): Add STL writer that support ASCII and binary format`)

**Comment by thomas-beznik** [comment]
Hello,

Thank you for the feedback, I have incorporated it and made a new branch and pull request to make things easier with re-writing the commit history.

**Comment by finetjul** [comment]
Noted. You could have force pushed it. It would have overwrite this current MR

**Comment by thomas-beznik** [comment]
Okay good to know, I'm not yet very fluent with pull requests!

**Pull request closed without merging**
