### PR TITLE
fix(reslicecursor): keep correct viewUp on rotation

### PR DESCRIPTION
**Pull request by laurennlam**
### Context
Setup correct viewup on old ResliceCursor widget in order to be consistent with the new one

@finetjul

### CODE REVIEW

**Comment by finetjul** [comment]
Does it behave the same as in the new reslice cursor widget ?

**Comment by laurennlam** [comment]
Yes. Here is a capture of the old updated widget:
image


Here is the new one:
image

Co concerning the view up, it's ok. There are still one difference, but t concerns the camera position, not the view up as you can see in the view with green/red lines

**Comment by finetjul** [comment]
Understood.

What's the issue with the camera position ?

**Comment by laurennlam** [comment]
It seems to be a sign issue but I didn't investigate it.

**Pull request merged**
