### PR TITLE
Add protocol dynamically

### PR DESCRIPTION
**Pull request by jourdain**
### Context

Provide example for https://github.com/Kitware/vtk-js/issues/1940

### Testing

Still WIP as the RenderWindow remain white...

@martinken can you take a look? I think I did the core part that you needed. Let me know if you need me to change something. I let you take over.

### CODE REVIEW

**Comment by martinken** [comment]
Fixed a couple issues. It renders now but there are still a couple positioning issues, one related to scroll bars I believe and the other just where the text is positioned but probably simple for you to fix.

**Comment by martinken** [comment]
@jourdain softer colors
```
C:\Users\ken.martin\Documents\vtkjs\vtk-js>git diff
diff --git a/Examples/Rendering/ManyRenderers/index.js b/Examples/Rendering/ManyRenderers/index.js
index 0f3e14ef84..201e4371c5 100644
--- a/Examples/Rendering/ManyRenderers/index.js
+++ b/Examples/Rendering/ManyRenderers/index.js
@@ -39,28 +39,28 @@ addMesh('Cylinder', vtkCylinderSource.newInstance());

 const properties = [
   {
-    name: '- Solid Red',
-    properties: { color: [1, 0, 0] },
+    name: '- Red',
+    properties: { color: [1, 0.5, 0.5] },
   },
   {
-    name: 'Edge - Solid Blue',
-    properties: { edgeVisibility: true, color: [0, 0, 1] },
+    name: 'Edge - Red',
+    properties: { edgeVisibility: true, color: [1, 0.5, 0.5] },
   },
   {
-    name: '- Solid Green',
-    properties: { color: [0, 1, 0] },
+    name: '- Blue',
+    properties: { color: [0.5, 0.5, 1] },
   },
   {
-    name: 'Edge - Solid Red',
-    properties: { edgeVisibility: true, color: [1, 0, 0] },
+    name: 'Edge - Green',
+    properties: { edgeVisibility: true, color: [0.5, 1, 0.5] },
   },
   {
-    name: '- Solid Blue',
-    properties: { color: [0, 0, 1] },
+    name: '- Green',
+    properties: { color: [0.5, 1, 0.5] },
   },
   {
-    name: 'Edge - Solid Green',
-    properties: { edgeVisibility: true, color: [0, 1, 0] },
+    name: 'Edge - Blue',
+    properties: { edgeVisibility: true, color: [0.5, 0.5, 1] },
   },
 ];

@@ -69,12 +69,13 @@ const properties = [
 // ----------------------------------------------------------------------------

 const colors = [
-  [0, 0, 0],
-  [1, 0, 0],
-  [0, 1, 0],
-  [0, 0, 1],
-  [0.5, 0.5, 0.5],
-  [1, 1, 1],
+  [0.3, 0.3, 0.3],
+  [0.6, 0.3, 0.4],
+  [0.3, 0.6, 0.4],
+  [0.8, 0.8, 0.8],
+  [0.6, 0.3, 0.6],
+  [0.4, 0.6, 0.3],
+  [0.4, 0.3, 0.6],
 ];

 // ----------------------------------------------------------------------------
(END)
```

**Comment by martinken** [comment]
image

**Comment by jourdain** [comment]
Wow this is supper cool

**Comment by jourdain** [comment]
BTW, I'm off this week so you can still do push changes if you like

**Comment by jourdain** [comment]
I might be able to fix the current pb with just some css.

**Comment by martinken** [comment]
No worries, I'm heading back to C++ land for a couple weeks so no rush.  I'll push my color changes though.

**Comment by martinken** [comment]
Wow there was a bug where specular lighting was ignored for WebGL.

**Comment by martinken** [comment]
I'm done with it

image

**Pull request merged**
