### PR TITLE
fix(rendering): Use texImage2D/3D on Mac WebGL2 for Norm16 textures

### PR DESCRIPTION
**Pull request by sankhesh**
### Context

On Apple platforms, WebKit doesn't doesn't seem to allocate textures of type short and unsigned short with `texStorage` and the `EXT_texture_norm16` extension. This change ensures that when this combination is used, texture allocation reverts to using `texImage2D/3D` calls with the norm16 extension.

### PR and Code Checklist

- [x] [semantic-release](https://github.com/semantic-release/semantic-release) commit messages
- [x] Run `npm run reformat` to have correctly formatted code

### Testing

- [x] This change adds or fixes unit tests 
- [x] Tested environment:
  - **vtk.js**: latest master
  - **OS**: macOS 
  - **Browser**: Chrome, Safari, Firefox

### CODE REVIEW

**Comment by sankhesh** [comment]
@floryst Could you please try this branch on your mac?

**Comment by floryst** [comment]
This works on my mac.

We will also need to test intel macs, since the issue does manifest there as well. I can run a test later today.

**Comment by billhoffman** [comment]
Is there a way to have CI test this type of thing with web development?

**Comment by sedghi** [comment]
This worked fine for me, can we merge it? 
image

**Comment by sedghi** [comment]
@billhoffman Much interested in your question, I haven't personally found any services that offer different browsers on different **hardwares**. We used to use browserStack for having different browser on different OS, and https://percy.io/

**Comment by floryst** [comment]
> Is there a way to have CI test this type of thing with web development?

It would be interesting to see if this would have been caught in a Github Actions macOS runner. Unfortunately, it is somewhat hardware specific.

> @floryst I have Intel mac and this worked fine for me, can we merge it?

Yep! Now that I have confirmation, I think we are good to go.

**Pull request merged**
