### PR TITLE
fix(Widgets): fix an issue with shared default objects

### PR DESCRIPTION
**Pull request by martinken**
had some shared objects that needed ot be moved out

### CODE REVIEW

**Comment by martinken** [comment]
Assuming the font properties are intended to be independent for each instance. ala https://github.com/Kitware/vtk-js/issues/1751#issuecomment-785411007

**Review by floryst — APPROVED** [review]
LGTM

One suggestion: if we wish to support partial initial values for objects, e.g. specifying only `fontColor` for `selectLabelStyle`, we could do something like the following snippet. If not, then this PR is still fine as-is.

```js
selectLabelStyle: {
  ...,
  lineSpace: 0.2,
  ...initialValues?.selectLabelStyle,
},
...
```

**Comment by finetjul** [comment]
> ```js
> selectLabelStyle: {
>   ...
>   lineSpace: 0.2,
>   ...initialValues?.selectLabelStyle,
> },
> ...
> ```

@floryst , are you suggesting something like that ?
```
return {
  ...
  selectLabelStyle: {
   fontColor: ...
    ...,
    lineSpace: 0.2,
    ...initialValues?.selectLabelStyle,
  },
  ...initialValues
};
```
If  `initialValue` is  `{selectLabelStyle: {lineSpace: 0.4}}`, won't you end up with : 
```
{
  ...,
  selectLabelStyle: {
    lineSpace: 0.4
  }
}
```
instead of:
```
{
  ...,
  selectLabelStyle: {
    fontColor: ...
    ...
    lineSpace: 0.4
  }
}
```
?

**Comment by jourdain** [comment]
```
function defaultValues(initialValues) {
  return {
    // container: null,
    labelText: '',
    textAlign: TextAlign.LEFT,
    verticalAlign: VerticalAlign.BOTTOM,
    ...initialValues,
    labelStyle: {
      fontColor: 'white',
      fontStyle: 'normal',
      fontSize: 15,
      fontFamily: 'Arial',
      strokeColor: 'black',
      strokeSize: 1,
      lineSpace: 0.2,
      ...initialValues?.labelStyle,
    },
    selectLabelStyle: {
      fontColor: 'rgb(0, 255, 0)',
      fontStyle: 'normal',
      fontSize: 15,
      fontFamily: 'Arial',
      strokeColor: 'black',
      strokeSize: 1,
      lineSpace: 0.2,
     ...initialValues?.selectLabelStyle,
    },
  };
}
```

**Pull request merged**
